# SQL-Front 5.1  (Build 4.16)

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE */;
/*!40101 SET SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES */;
/*!40103 SET SQL_NOTES='ON' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;


# Host: localhost    Database: tweetsentiment
# ------------------------------------------------------
# Server version 5.5.5-10.4.11-MariaDB

USE `tweetsentiment`;

#
# Dumping data for table slangwords
#

LOCK TABLES `slangwords` WRITE;
/*!40000 ALTER TABLE `slangwords` DISABLE KEYS */;
INSERT INTO `slangwords` VALUES (1,'aberasi','abrasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (2,'nuhun','maaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (3,'accu','aki',NULL,NULL);
INSERT INTO `slangwords` VALUES (4,'adap','adab',NULL,NULL);
INSERT INTO `slangwords` VALUES (5,'adiguna','adiguna',NULL,NULL);
INSERT INTO `slangwords` VALUES (6,'admin','administrator',NULL,NULL);
INSERT INTO `slangwords` VALUES (7,'adpokat','advokat',NULL,NULL);
INSERT INTO `slangwords` VALUES (8,'adzan','azan',NULL,NULL);
INSERT INTO `slangwords` VALUES (9,'afdol','afdal',NULL,NULL);
INSERT INTO `slangwords` VALUES (10,'agamis','agamais',NULL,NULL);
INSERT INTO `slangwords` VALUES (11,'ajektif','adjektif',NULL,NULL);
INSERT INTO `slangwords` VALUES (12,'ajimat','azimat',NULL,NULL);
INSERT INTO `slangwords` VALUES (13,'akhirulkalam','akhirulkalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (14,'aktuil','aktual',NULL,NULL);
INSERT INTO `slangwords` VALUES (15,'amandemen','amendemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (16,'ambeyen','ambeien',NULL,NULL);
INSERT INTO `slangwords` VALUES (17,'ambulan','ambulans',NULL,NULL);
INSERT INTO `slangwords` VALUES (18,'ambulance','ambulans',NULL,NULL);
INSERT INTO `slangwords` VALUES (19,'analisa','analisis',NULL,NULL);
INSERT INTO `slangwords` VALUES (20,'anestesia','anestesi',NULL,NULL);
INSERT INTO `slangwords` VALUES (21,'ansambel','ensambel',NULL,NULL);
INSERT INTO `slangwords` VALUES (22,'antarumatberagama','antarumatberagama',NULL,NULL);
INSERT INTO `slangwords` VALUES (23,'antene','antenna',NULL,NULL);
INSERT INTO `slangwords` VALUES (24,'antri','antre',NULL,NULL);
INSERT INTO `slangwords` VALUES (25,'aparatur','aparat',NULL,NULL);
INSERT INTO `slangwords` VALUES (26,'aplus','aplaus',NULL,NULL);
INSERT INTO `slangwords` VALUES (27,'apotik','apotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (28,'aquades','akuades',NULL,NULL);
INSERT INTO `slangwords` VALUES (29,'asal-muasal','asal mula',NULL,NULL);
INSERT INTO `slangwords` VALUES (30,'asesori','aksesori',NULL,NULL);
INSERT INTO `slangwords` VALUES (31,'astronot','astronaut',NULL,NULL);
INSERT INTO `slangwords` VALUES (32,'atheis','ateis',NULL,NULL);
INSERT INTO `slangwords` VALUES (33,'atmosfir','atmosfer',NULL,NULL);
INSERT INTO `slangwords` VALUES (34,'audiens','audiensi',NULL,NULL);
INSERT INTO `slangwords` VALUES (35,'autobiografi','otobiografi',NULL,NULL);
INSERT INTO `slangwords` VALUES (36,'automatis','otomatis',NULL,NULL);
INSERT INTO `slangwords` VALUES (37,'automatic','otomatis',NULL,NULL);
INSERT INTO `slangwords` VALUES (38,'azas','asas',NULL,NULL);
INSERT INTO `slangwords` VALUES (39,'balsem','balsam',NULL,NULL);
INSERT INTO `slangwords` VALUES (40,'bangker','bungker',NULL,NULL);
INSERT INTO `slangwords` VALUES (41,'baqa','baka',NULL,NULL);
INSERT INTO `slangwords` VALUES (42,'barzah','alamkubur',NULL,NULL);
INSERT INTO `slangwords` VALUES (43,'batalyon','batalion',NULL,NULL);
INSERT INTO `slangwords` VALUES (44,'baterei','baterai',NULL,NULL);
INSERT INTO `slangwords` VALUES (45,'bathil','batil',NULL,NULL);
INSERT INTO `slangwords` VALUES (46,'bazaar','bazar',NULL,NULL);
INSERT INTO `slangwords` VALUES (47,'belangko','blangko',NULL,NULL);
INSERT INTO `slangwords` VALUES (48,'belender','blender',NULL,NULL);
INSERT INTO `slangwords` VALUES (49,'bengkoang','bengkuang',NULL,NULL);
INSERT INTO `slangwords` VALUES (50,'bengkowang','bengkuang',NULL,NULL);
INSERT INTO `slangwords` VALUES (51,'bhiku','biksu',NULL,NULL);
INSERT INTO `slangwords` VALUES (52,'bis','bus',NULL,NULL);
INSERT INTO `slangwords` VALUES (53,'blokir','blockade',NULL,NULL);
INSERT INTO `slangwords` VALUES (54,'bolpoint','bolpoin',NULL,NULL);
INSERT INTO `slangwords` VALUES (55,'bolpen','bolpoin',NULL,NULL);
INSERT INTO `slangwords` VALUES (56,'polpen','bolpoin',NULL,NULL);
INSERT INTO `slangwords` VALUES (57,'bongkok','bungkuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (58,'brandal','berandal',NULL,NULL);
INSERT INTO `slangwords` VALUES (59,'brangkas','brankas',NULL,NULL);
INSERT INTO `slangwords` VALUES (60,'brengsek','berengsek',NULL,NULL);
INSERT INTO `slangwords` VALUES (61,'brewok','bewok',NULL,NULL);
INSERT INTO `slangwords` VALUES (62,'budeg','budek',NULL,NULL);
INSERT INTO `slangwords` VALUES (63,'budget','bujet',NULL,NULL);
INSERT INTO `slangwords` VALUES (64,'cabe','cabai',NULL,NULL);
INSERT INTO `slangwords` VALUES (65,'cafetaria','kafetaria',NULL,NULL);
INSERT INTO `slangwords` VALUES (66,'cape','capai',NULL,NULL);
INSERT INTO `slangwords` VALUES (67,'capek','capai',NULL,NULL);
INSERT INTO `slangwords` VALUES (68,'cengkeh','cengkih',NULL,NULL);
INSERT INTO `slangwords` VALUES (69,'cengkram','cengkeram',NULL,NULL);
INSERT INTO `slangwords` VALUES (70,'cengkrama','bersenang-senang',NULL,NULL);
INSERT INTO `slangwords` VALUES (71,'cengkerama','bersenang-senang',NULL,NULL);
INSERT INTO `slangwords` VALUES (72,'cidera','cedera',NULL,NULL);
INSERT INTO `slangwords` VALUES (73,'cinderamata','cenderamata',NULL,NULL);
INSERT INTO `slangwords` VALUES (74,'clien','klien',NULL,NULL);
INSERT INTO `slangwords` VALUES (75,'clurit','celurit',NULL,NULL);
INSERT INTO `slangwords` VALUES (76,'cockpit','kokpit',NULL,NULL);
INSERT INTO `slangwords` VALUES (77,'coklat','cokelat',NULL,NULL);
INSERT INTO `slangwords` VALUES (78,'combro','comro',NULL,NULL);
INSERT INTO `slangwords` VALUES (79,'debet','debit',NULL,NULL);
INSERT INTO `slangwords` VALUES (80,'debitur','debitor',NULL,NULL);
INSERT INTO `slangwords` VALUES (81,'defiasi','deviasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (82,'dekrit','dekret',NULL,NULL);
INSERT INTO `slangwords` VALUES (83,'deodorant','deodorant',NULL,NULL);
INSERT INTO `slangwords` VALUES (84,'depo','depot',NULL,NULL);
INSERT INTO `slangwords` VALUES (85,'deputy','deputi',NULL,NULL);
INSERT INTO `slangwords` VALUES (86,'design','desain',NULL,NULL);
INSERT INTO `slangwords` VALUES (87,'disain','desain',NULL,NULL);
INSERT INTO `slangwords` VALUES (88,'despenser','dispenser',NULL,NULL);
INSERT INTO `slangwords` VALUES (89,'destilasi','distilasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (90,'deterjen','detergen',NULL,NULL);
INSERT INTO `slangwords` VALUES (91,'detil','detail',NULL,NULL);
INSERT INTO `slangwords` VALUES (92,'detel','detail',NULL,NULL);
INSERT INTO `slangwords` VALUES (93,'deviden','dividen',NULL,NULL);
INSERT INTO `slangwords` VALUES (94,'dharma','darma',NULL,NULL);
INSERT INTO `slangwords` VALUES (95,'diagnosa','diagnosis',NULL,NULL);
INSERT INTO `slangwords` VALUES (96,'diagnose','diagnosis',NULL,NULL);
INSERT INTO `slangwords` VALUES (97,'disco','disko',NULL,NULL);
INSERT INTO `slangwords` VALUES (98,'diskotik','diskotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (99,'diskripsi','deskripsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (100,'dollar','dolar',NULL,NULL);
INSERT INTO `slangwords` VALUES (101,'domain','domein',NULL,NULL);
INSERT INTO `slangwords` VALUES (102,'dramatisir','dramatisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (103,'duren','durian',NULL,NULL);
INSERT INTO `slangwords` VALUES (104,'dzat','zat',NULL,NULL);
INSERT INTO `slangwords` VALUES (105,'dzikir','zikir',NULL,NULL);
INSERT INTO `slangwords` VALUES (106,'faham','paham',NULL,NULL);
INSERT INTO `slangwords` VALUES (107,'faksinasi','vaksinasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (108,'fakum','vakum',NULL,NULL);
INSERT INTO `slangwords` VALUES (109,'vacuum','vakum',NULL,NULL);
INSERT INTO `slangwords` VALUES (110,'falid','valid',NULL,NULL);
INSERT INTO `slangwords` VALUES (111,'faqih','fakih',NULL,NULL);
INSERT INTO `slangwords` VALUES (112,'fas','vas',NULL,NULL);
INSERT INTO `slangwords` VALUES (113,'ferri','feri',NULL,NULL);
INSERT INTO `slangwords` VALUES (114,'fery','feri',NULL,NULL);
INSERT INTO `slangwords` VALUES (115,'filsof','filosof',NULL,NULL);
INSERT INTO `slangwords` VALUES (116,'filsuf','filosof',NULL,NULL);
INSERT INTO `slangwords` VALUES (117,'finish','finis',NULL,NULL);
INSERT INTO `slangwords` VALUES (118,'foklor','folklore',NULL,NULL);
INSERT INTO `slangwords` VALUES (119,'formil','formal',NULL,NULL);
INSERT INTO `slangwords` VALUES (120,'foto copy','fotokopi',NULL,NULL);
INSERT INTO `slangwords` VALUES (121,'foto kopi','fotokopi',NULL,NULL);
INSERT INTO `slangwords` VALUES (122,'photo copy','fotokopi',NULL,NULL);
INSERT INTO `slangwords` VALUES (123,'foto studio','studio foto',NULL,NULL);
INSERT INTO `slangwords` VALUES (124,'fotosintesa','fotosintesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (125,'frasa','frase',NULL,NULL);
INSERT INTO `slangwords` VALUES (126,'frekwensi','frekuensi',NULL,NULL);
INSERT INTO `slangwords` VALUES (127,'fron','front',NULL,NULL);
INSERT INTO `slangwords` VALUES (128,'frustasi','frustrasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (129,'galleri','galeri',NULL,NULL);
INSERT INTO `slangwords` VALUES (130,'gallery','galeri',NULL,NULL);
INSERT INTO `slangwords` VALUES (131,'geladiresik','geladi bersih',NULL,NULL);
INSERT INTO `slangwords` VALUES (132,'gladibersih','geladi bersih',NULL,NULL);
INSERT INTO `slangwords` VALUES (133,'genius','jenius',NULL,NULL);
INSERT INTO `slangwords` VALUES (134,'genteng','genting',NULL,NULL);
INSERT INTO `slangwords` VALUES (135,'gep','gap',NULL,NULL);
INSERT INTO `slangwords` VALUES (136,'gepok','kapok',NULL,NULL);
INSERT INTO `slangwords` VALUES (137,'ghaib','gaib',NULL,NULL);
INSERT INTO `slangwords` VALUES (138,'ghoib','gaib',NULL,NULL);
INSERT INTO `slangwords` VALUES (139,'gladi','geladi',NULL,NULL);
INSERT INTO `slangwords` VALUES (140,'glamour','glamor',NULL,NULL);
INSERT INTO `slangwords` VALUES (141,'glondong','gelondong',NULL,NULL);
INSERT INTO `slangwords` VALUES (142,'glosary','glosarium',NULL,NULL);
INSERT INTO `slangwords` VALUES (143,'goa','gua',NULL,NULL);
INSERT INTO `slangwords` VALUES (144,'goncang','guncang',NULL,NULL);
INSERT INTO `slangwords` VALUES (145,'greget','gereget',NULL,NULL);
INSERT INTO `slangwords` VALUES (146,'grendel','gerendel',NULL,NULL);
INSERT INTO `slangwords` VALUES (147,'griya','gria',NULL,NULL);
INSERT INTO `slangwords` VALUES (148,'grogol','gerogol',NULL,NULL);
INSERT INTO `slangwords` VALUES (149,'gudeg','gudek',NULL,NULL);
INSERT INTO `slangwords` VALUES (150,'hakekat','hakikat',NULL,NULL);
INSERT INTO `slangwords` VALUES (151,'handal','andal',NULL,NULL);
INSERT INTO `slangwords` VALUES (152,'hapal','hafal',NULL,NULL);
INSERT INTO `slangwords` VALUES (153,'hektar','hektare',NULL,NULL);
INSERT INTO `slangwords` VALUES (154,'hempas','empas',NULL,NULL);
INSERT INTO `slangwords` VALUES (155,'hetrogen','heterogen',NULL,NULL);
INSERT INTO `slangwords` VALUES (156,'higiena','higienis',NULL,NULL);
INSERT INTO `slangwords` VALUES (157,'hygiene','higienis',NULL,NULL);
INSERT INTO `slangwords` VALUES (158,'himbau','imbau',NULL,NULL);
INSERT INTO `slangwords` VALUES (159,'himpit','impit',NULL,NULL);
INSERT INTO `slangwords` VALUES (160,'hingar-bingar','ingar-bingar',NULL,NULL);
INSERT INTO `slangwords` VALUES (161,'hipotesa','hipotesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (162,'hipotik','hipotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (163,'hirarki','hierarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (164,'hisap','isap',NULL,NULL);
INSERT INTO `slangwords` VALUES (165,'hutang','utang',NULL,NULL);
INSERT INTO `slangwords` VALUES (166,'hybrida','hibrida',NULL,NULL);
INSERT INTO `slangwords` VALUES (167,'hymne','himne',NULL,NULL);
INSERT INTO `slangwords` VALUES (168,'iâ€™tikaf','iktikaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (169,'idiil','ideal',NULL,NULL);
INSERT INTO `slangwords` VALUES (170,'idial','ideal',NULL,NULL);
INSERT INTO `slangwords` VALUES (171,'idiologi','ideologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (172,'ijasah','ijazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (173,'ijin','izin',NULL,NULL);
INSERT INTO `slangwords` VALUES (174,'ikhwal','ihwal',NULL,NULL);
INSERT INTO `slangwords` VALUES (175,'iklas','ikhlas',NULL,NULL);
INSERT INTO `slangwords` VALUES (176,'ihlas','ikhlas',NULL,NULL);
INSERT INTO `slangwords` VALUES (177,'illusi','ilusi',NULL,NULL);
INSERT INTO `slangwords` VALUES (178,'import','impor',NULL,NULL);
INSERT INTO `slangwords` VALUES (179,'income','pendapatan',NULL,NULL);
INSERT INTO `slangwords` VALUES (180,'influensa','influenza',NULL,NULL);
INSERT INTO `slangwords` VALUES (181,'influenza','influenza',NULL,NULL);
INSERT INTO `slangwords` VALUES (182,'infra merah','inframerah',NULL,NULL);
INSERT INTO `slangwords` VALUES (183,'inpus','infus',NULL,NULL);
INSERT INTO `slangwords` VALUES (184,'insyaf','insaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (185,'intel','intelijen',NULL,NULL);
INSERT INTO `slangwords` VALUES (186,'inteligen','intelijen',NULL,NULL);
INSERT INTO `slangwords` VALUES (187,'intelejensi','intelegensi',NULL,NULL);
INSERT INTO `slangwords` VALUES (188,'inten','intens',NULL,NULL);
INSERT INTO `slangwords` VALUES (189,'interest','interes',NULL,NULL);
INSERT INTO `slangwords` VALUES (190,'intermezo','intermeso',NULL,NULL);
INSERT INTO `slangwords` VALUES (191,'interograsi','interogasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (192,'interospeksi','introspeksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (193,'interprestasi','interpretasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (194,'intrupsi','interupsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (195,'islamiyah','islamiah',NULL,NULL);
INSERT INTO `slangwords` VALUES (196,'isteri','istri',NULL,NULL);
INSERT INTO `slangwords` VALUES (197,'istighfar','istigfar',NULL,NULL);
INSERT INTO `slangwords` VALUES (198,'jagad','jagat',NULL,NULL);
INSERT INTO `slangwords` VALUES (199,'jahiliyah','jahiliah',NULL,NULL);
INSERT INTO `slangwords` VALUES (200,'jaman','zaman',NULL,NULL);
INSERT INTO `slangwords` VALUES (201,'jejer','jajar',NULL,NULL);
INSERT INTO `slangwords` VALUES (202,'jemaah','jamaah',NULL,NULL);
INSERT INTO `slangwords` VALUES (203,'jemaat','jamaah',NULL,NULL);
INSERT INTO `slangwords` VALUES (204,'jenasah','jenazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (205,'jendral','jenderal',NULL,NULL);
INSERT INTO `slangwords` VALUES (206,'jenius','genius',NULL,NULL);
INSERT INTO `slangwords` VALUES (207,'jerembap','jerembab',NULL,NULL);
INSERT INTO `slangwords` VALUES (208,'jogging','jogging',NULL,NULL);
INSERT INTO `slangwords` VALUES (209,'joint','join',NULL,NULL);
INSERT INTO `slangwords` VALUES (210,'kacamata','kacamata',NULL,NULL);
INSERT INTO `slangwords` VALUES (211,'kadaluwarsa','kedaluwarsa',NULL,NULL);
INSERT INTO `slangwords` VALUES (212,'kaedah','kaidah',NULL,NULL);
INSERT INTO `slangwords` VALUES (213,'kakatua','kakaktua',NULL,NULL);
INSERT INTO `slangwords` VALUES (214,'kaleidioskop','kaleidoskop',NULL,NULL);
INSERT INTO `slangwords` VALUES (215,'kameramen','kamerawan',NULL,NULL);
INSERT INTO `slangwords` VALUES (216,'kameraman','kamerawan',NULL,NULL);
INSERT INTO `slangwords` VALUES (217,'kamuplase','kamuflase',NULL,NULL);
INSERT INTO `slangwords` VALUES (218,'kangker','kanker',NULL,NULL);
INSERT INTO `slangwords` VALUES (219,'kantung','kantong',NULL,NULL);
INSERT INTO `slangwords` VALUES (220,'kaos','kaus',NULL,NULL);
INSERT INTO `slangwords` VALUES (221,'katagori','kategori',NULL,NULL);
INSERT INTO `slangwords` VALUES (222,'katalisa','katalisis',NULL,NULL);
INSERT INTO `slangwords` VALUES (223,'katring','catering',NULL,NULL);
INSERT INTO `slangwords` VALUES (224,'cathering','catering',NULL,NULL);
INSERT INTO `slangwords` VALUES (225,'keburu','terburuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (226,'kdlmn','kedalaman',NULL,NULL);
INSERT INTO `slangwords` VALUES (227,'kedele','kedelai',NULL,NULL);
INSERT INTO `slangwords` VALUES (228,'kelep','klep',NULL,NULL);
INSERT INTO `slangwords` VALUES (229,'kemana','kemana',NULL,NULL);
INSERT INTO `slangwords` VALUES (230,'kenalpot','knalpot',NULL,NULL);
INSERT INTO `slangwords` VALUES (231,'kendor','kendur',NULL,NULL);
INSERT INTO `slangwords` VALUES (232,'kenop','knop',NULL,NULL);
INSERT INTO `slangwords` VALUES (233,'kerdip','kedip',NULL,NULL);
INSERT INTO `slangwords` VALUES (234,'kerdus','kardus',NULL,NULL);
INSERT INTO `slangwords` VALUES (235,'kerjasama','kerjasama',NULL,NULL);
INSERT INTO `slangwords` VALUES (236,'ketawa','tertawa',NULL,NULL);
INSERT INTO `slangwords` VALUES (237,'ketemu','bertemu',NULL,NULL);
INSERT INTO `slangwords` VALUES (238,'kharisma','karisma',NULL,NULL);
INSERT INTO `slangwords` VALUES (239,'klorofil','kloropil',NULL,NULL);
INSERT INTO `slangwords` VALUES (240,'kloter','keloter',NULL,NULL);
INSERT INTO `slangwords` VALUES (241,'koboy','koboi',NULL,NULL);
INSERT INTO `slangwords` VALUES (242,'kocar-kacir','kucar-kacir',NULL,NULL);
INSERT INTO `slangwords` VALUES (243,'komersil','komersial',NULL,NULL);
INSERT INTO `slangwords` VALUES (244,'komfirmasi','konfirmasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (245,'komoditi','komoditas',NULL,NULL);
INSERT INTO `slangwords` VALUES (246,'konggres','kongres',NULL,NULL);
INSERT INTO `slangwords` VALUES (247,'kongkret','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (248,'kongkrit','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (249,'konkrit','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (250,'konsleting','korsleting',NULL,NULL);
INSERT INTO `slangwords` VALUES (251,'kram','keram',NULL,NULL);
INSERT INTO `slangwords` VALUES (252,'kramat','keramat',NULL,NULL);
INSERT INTO `slangwords` VALUES (253,'kreatifitas','kreativitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (254,'kresek','keresek',NULL,NULL);
INSERT INTO `slangwords` VALUES (255,'kwitansi','kuitansi',NULL,NULL);
INSERT INTO `slangwords` VALUES (256,'kwitangsi','kuitansi',NULL,NULL);
INSERT INTO `slangwords` VALUES (257,'lajim','lazim',NULL,NULL);
INSERT INTO `slangwords` VALUES (258,'lasim','lazim',NULL,NULL);
INSERT INTO `slangwords` VALUES (259,'lapal','lafal',NULL,NULL);
INSERT INTO `slangwords` VALUES (260,'rapal','lafal',NULL,NULL);
INSERT INTO `slangwords` VALUES (261,'lasykar','laskar',NULL,NULL);
INSERT INTO `slangwords` VALUES (262,'legalisir','legalisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (263,'lemari','almari',NULL,NULL);
INSERT INTO `slangwords` VALUES (264,'lembap','lembab',NULL,NULL);
INSERT INTO `slangwords` VALUES (265,'leukimia','leukemia',NULL,NULL);
INSERT INTO `slangwords` VALUES (266,'limpha','limfa',NULL,NULL);
INSERT INTO `slangwords` VALUES (267,'limpa','limfa',NULL,NULL);
INSERT INTO `slangwords` VALUES (268,'linier','linear',NULL,NULL);
INSERT INTO `slangwords` VALUES (269,'lobang','lubang',NULL,NULL);
INSERT INTO `slangwords` VALUES (270,'lokalisir','lokalisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (271,'losin','lusin',NULL,NULL);
INSERT INTO `slangwords` VALUES (272,'dozen','lusin',NULL,NULL);
INSERT INTO `slangwords` VALUES (273,'dosin','lusin',NULL,NULL);
INSERT INTO `slangwords` VALUES (274,'lotere','lotre',NULL,NULL);
INSERT INTO `slangwords` VALUES (275,'maâ€™af','maaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (276,'mabok','mabuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (277,'maag','mag',NULL,NULL);
INSERT INTO `slangwords` VALUES (278,'mahnet','magnet',NULL,NULL);
INSERT INTO `slangwords` VALUES (279,'mahaesa','mahaesa',NULL,NULL);
INSERT INTO `slangwords` VALUES (280,'maha esa','mahaesa',NULL,NULL);
INSERT INTO `slangwords` VALUES (281,'mahakuasa','mahakuasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (282,'maha kuasa','mahakuasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (283,'maha pengasih','mahapengasih',NULL,NULL);
INSERT INTO `slangwords` VALUES (284,'mahapengasih','mahapengasih',NULL,NULL);
INSERT INTO `slangwords` VALUES (285,'makroekonomi','makroekonomi',NULL,NULL);
INSERT INTO `slangwords` VALUES (286,'mampet','mampat',NULL,NULL);
INSERT INTO `slangwords` VALUES (287,'manager','manajer',NULL,NULL);
INSERT INTO `slangwords` VALUES (288,'mangkok','mangkuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (289,'mantera','mantra',NULL,NULL);
INSERT INTO `slangwords` VALUES (290,'marathon','marathon',NULL,NULL);
INSERT INTO `slangwords` VALUES (291,'margarine','margarin',NULL,NULL);
INSERT INTO `slangwords` VALUES (292,'massal','masal',NULL,NULL);
INSERT INTO `slangwords` VALUES (293,'mentari','matahari',NULL,NULL);
INSERT INTO `slangwords` VALUES (294,'melody','melodi',NULL,NULL);
INSERT INTO `slangwords` VALUES (295,'menyuci','mencuci',NULL,NULL);
INSERT INTO `slangwords` VALUES (296,'menterapkan','menerapkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (297,'meram','merem',NULL,NULL);
INSERT INTO `slangwords` VALUES (298,'metoda','metode',NULL,NULL);
INSERT INTO `slangwords` VALUES (299,'mie','mi',NULL,NULL);
INSERT INTO `slangwords` VALUES (300,'moto','motto',NULL,NULL);
INSERT INTO `slangwords` VALUES (301,'musyafir','musafir',NULL,NULL);
INSERT INTO `slangwords` VALUES (302,'nafas','napas',NULL,NULL);
INSERT INTO `slangwords` VALUES (303,'nahas','naas',NULL,NULL);
INSERT INTO `slangwords` VALUES (304,'nahkoda','nakhoda',NULL,NULL);
INSERT INTO `slangwords` VALUES (305,'nakoda','nakhoda',NULL,NULL);
INSERT INTO `slangwords` VALUES (306,'nasehat','nasihat',NULL,NULL);
INSERT INTO `slangwords` VALUES (307,'netralisir','netralisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (308,'netto','neto',NULL,NULL);
INSERT INTO `slangwords` VALUES (309,'notulen','notula',NULL,NULL);
INSERT INTO `slangwords` VALUES (310,'omset','omzet',NULL,NULL);
INSERT INTO `slangwords` VALUES (311,'ongseng','gongseng',NULL,NULL);
INSERT INTO `slangwords` VALUES (312,'oseng-oseng','gongseng',NULL,NULL);
INSERT INTO `slangwords` VALUES (313,'organisir','organisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (314,'orisinil','orisinal',NULL,NULL);
INSERT INTO `slangwords` VALUES (315,'orkhestra','orkestra',NULL,NULL);
INSERT INTO `slangwords` VALUES (316,'orchestra','orkestra',NULL,NULL);
INSERT INTO `slangwords` VALUES (317,'otentik','autentik',NULL,NULL);
INSERT INTO `slangwords` VALUES (318,'otopsi','autopsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (319,'palem','palma',NULL,NULL);
INSERT INTO `slangwords` VALUES (320,'pamfelet','pamflet',NULL,NULL);
INSERT INTO `slangwords` VALUES (321,'famplet','pamflet',NULL,NULL);
INSERT INTO `slangwords` VALUES (322,'pancaindra','pancaindera',NULL,NULL);
INSERT INTO `slangwords` VALUES (323,'pangkreas','pankreas',NULL,NULL);
INSERT INTO `slangwords` VALUES (324,'panitra','panitera',NULL,NULL);
INSERT INTO `slangwords` VALUES (325,'pas foto','pasfoto',NULL,NULL);
INSERT INTO `slangwords` VALUES (326,'pas photo','pasfoto',NULL,NULL);
INSERT INTO `slangwords` VALUES (327,'pasca-panen','pascapanen',NULL,NULL);
INSERT INTO `slangwords` VALUES (328,'pasport','paspor',NULL,NULL);
INSERT INTO `slangwords` VALUES (329,'pavilyun','anjungan',NULL,NULL);
INSERT INTO `slangwords` VALUES (330,'paviliyun','anjugan',NULL,NULL);
INSERT INTO `slangwords` VALUES (331,'pebruari','februari',NULL,NULL);
INSERT INTO `slangwords` VALUES (332,'pedes','pedas',NULL,NULL);
INSERT INTO `slangwords` VALUES (333,'pelaminan','pelamin',NULL,NULL);
INSERT INTO `slangwords` VALUES (334,'pengrajin','perajin',NULL,NULL);
INSERT INTO `slangwords` VALUES (335,'perduli','peduli',NULL,NULL);
INSERT INTO `slangwords` VALUES (336,'photo','foto',NULL,NULL);
INSERT INTO `slangwords` VALUES (337,'piranti','peranti',NULL,NULL);
INSERT INTO `slangwords` VALUES (338,'pirsawan','pemirsa',NULL,NULL);
INSERT INTO `slangwords` VALUES (339,'plesir','pelesir',NULL,NULL);
INSERT INTO `slangwords` VALUES (340,'plonco','pelonco',NULL,NULL);
INSERT INTO `slangwords` VALUES (341,'plontos','pelontos',NULL,NULL);
INSERT INTO `slangwords` VALUES (342,'qolam','kalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (343,'qalam','kalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (344,'qolbu','kalbu',NULL,NULL);
INSERT INTO `slangwords` VALUES (345,'qomat','kamat',NULL,NULL);
INSERT INTO `slangwords` VALUES (346,'quraisy','kuraisy',NULL,NULL);
INSERT INTO `slangwords` VALUES (347,'ramadhan','ramadan',NULL,NULL);
INSERT INTO `slangwords` VALUES (348,'romadhon','ramadan',NULL,NULL);
INSERT INTO `slangwords` VALUES (349,'romadlon','ramadan',NULL,NULL);
INSERT INTO `slangwords` VALUES (350,'rangking','ranking',NULL,NULL);
INSERT INTO `slangwords` VALUES (351,'rengking','ranking',NULL,NULL);
INSERT INTO `slangwords` VALUES (352,'ranzel','ransel',NULL,NULL);
INSERT INTO `slangwords` VALUES (353,'rangsel','ransel',NULL,NULL);
INSERT INTO `slangwords` VALUES (354,'rapih','rapi',NULL,NULL);
INSERT INTO `slangwords` VALUES (355,'rapot','rapor',NULL,NULL);
INSERT INTO `slangwords` VALUES (356,'raport','rapor',NULL,NULL);
INSERT INTO `slangwords` VALUES (357,'rasia','razia',NULL,NULL);
INSERT INTO `slangwords` VALUES (358,'rajia','razia',NULL,NULL);
INSERT INTO `slangwords` VALUES (359,'rasialist','rasialis',NULL,NULL);
INSERT INTO `slangwords` VALUES (360,'rasionil','rasional',NULL,NULL);
INSERT INTO `slangwords` VALUES (361,'rebo','rabu',NULL,NULL);
INSERT INTO `slangwords` VALUES (362,'rejeki','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (363,'rezki','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (364,'rizqi','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (365,'rekruit','rekrut',NULL,NULL);
INSERT INTO `slangwords` VALUES (366,'relif','relief',NULL,NULL);
INSERT INTO `slangwords` VALUES (367,'reptil','reptilia',NULL,NULL);
INSERT INTO `slangwords` VALUES (368,'resiko','risiko',NULL,NULL);
INSERT INTO `slangwords` VALUES (369,'respon','respons',NULL,NULL);
INSERT INTO `slangwords` VALUES (370,'restauran','restoran',NULL,NULL);
INSERT INTO `slangwords` VALUES (371,'restaurant','restoran',NULL,NULL);
INSERT INTO `slangwords` VALUES (372,'resum','resume',NULL,NULL);
INSERT INTO `slangwords` VALUES (373,'reumatik','rematik',NULL,NULL);
INSERT INTO `slangwords` VALUES (374,'riil','nyata',NULL,NULL);
INSERT INTO `slangwords` VALUES (375,'ritme','ritma',NULL,NULL);
INSERT INTO `slangwords` VALUES (376,'roh','ruh',NULL,NULL);
INSERT INTO `slangwords` VALUES (377,'ronsen','rontgen',NULL,NULL);
INSERT INTO `slangwords` VALUES (378,'route','rute',NULL,NULL);
INSERT INTO `slangwords` VALUES (379,'rubah','ubah',NULL,NULL);
INSERT INTO `slangwords` VALUES (380,'sahadat','syahadat',NULL,NULL);
INSERT INTO `slangwords` VALUES (381,'sahid','syahid',NULL,NULL);
INSERT INTO `slangwords` VALUES (382,'syahit','syahid',NULL,NULL);
INSERT INTO `slangwords` VALUES (383,'sahwat','syahwat',NULL,NULL);
INSERT INTO `slangwords` VALUES (384,'saklar','sakelar',NULL,NULL);
INSERT INTO `slangwords` VALUES (385,'sambel','sambal',NULL,NULL);
INSERT INTO `slangwords` VALUES (386,'sangsi','sanksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (387,'sanjak','sajak',NULL,NULL);
INSERT INTO `slangwords` VALUES (388,'sansekerta','sanskerta',NULL,NULL);
INSERT INTO `slangwords` VALUES (389,'saos','saus',NULL,NULL);
INSERT INTO `slangwords` VALUES (390,'saparila','sarsaparilla',NULL,NULL);
INSERT INTO `slangwords` VALUES (391,'saplemen','suplemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (392,'supplement','suplemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (393,'sate','satai',NULL,NULL);
INSERT INTO `slangwords` VALUES (394,'sekedar','sekadar',NULL,NULL);
INSERT INTO `slangwords` VALUES (395,'seksama','saksama',NULL,NULL);
INSERT INTO `slangwords` VALUES (396,'sekuler','secular',NULL,NULL);
INSERT INTO `slangwords` VALUES (397,'sentausa','sentosa',NULL,NULL);
INSERT INTO `slangwords` VALUES (398,'sepanduk','spanduk',NULL,NULL);
INSERT INTO `slangwords` VALUES (399,'sepesial','spesial',NULL,NULL);
INSERT INTO `slangwords` VALUES (400,'special','spesial',NULL,NULL);
INSERT INTO `slangwords` VALUES (401,'seprei','seprai',NULL,NULL);
INSERT INTO `slangwords` VALUES (402,'stress','stres',NULL,NULL);
INSERT INTO `slangwords` VALUES (403,'strip','setrip',NULL,NULL);
INSERT INTO `slangwords` VALUES (404,'strok','stroke',NULL,NULL);
INSERT INTO `slangwords` VALUES (405,'subsidair','subside',NULL,NULL);
INSERT INTO `slangwords` VALUES (406,'subtansi','substansi',NULL,NULL);
INSERT INTO `slangwords` VALUES (407,'subtitusi','substitusi',NULL,NULL);
INSERT INTO `slangwords` VALUES (408,'subyek','subjek',NULL,NULL);
INSERT INTO `slangwords` VALUES (409,'sukacita','sukacita',NULL,NULL);
INSERT INTO `slangwords` VALUES (410,'sup','sop',NULL,NULL);
INSERT INTO `slangwords` VALUES (411,'soup','sop',NULL,NULL);
INSERT INTO `slangwords` VALUES (412,'supir','sopir',NULL,NULL);
INSERT INTO `slangwords` VALUES (413,'surve','survei',NULL,NULL);
INSERT INTO `slangwords` VALUES (414,'survey','survei',NULL,NULL);
INSERT INTO `slangwords` VALUES (415,'sutra','sutera',NULL,NULL);
INSERT INTO `slangwords` VALUES (416,'syahdu','sahdu',NULL,NULL);
INSERT INTO `slangwords` VALUES (417,'syurga','surga',NULL,NULL);
INSERT INTO `slangwords` VALUES (418,'sorga','surga',NULL,NULL);
INSERT INTO `slangwords` VALUES (419,'tahta','takhta',NULL,NULL);
INSERT INTO `slangwords` VALUES (420,'tangker','tanker',NULL,NULL);
INSERT INTO `slangwords` VALUES (421,'tape','tapai',NULL,NULL);
INSERT INTO `slangwords` VALUES (422,'tapi','tetapi',NULL,NULL);
INSERT INTO `slangwords` VALUES (423,'tatto','tato',NULL,NULL);
INSERT INTO `slangwords` VALUES (424,'taubat','tobat',NULL,NULL);
INSERT INTO `slangwords` VALUES (425,'taulada/toladan','teladan',NULL,NULL);
INSERT INTO `slangwords` VALUES (426,'taxi','taksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (427,'tehnik','teknik',NULL,NULL);
INSERT INTO `slangwords` VALUES (428,'tekat','tekad',NULL,NULL);
INSERT INTO `slangwords` VALUES (429,'telor','telur',NULL,NULL);
INSERT INTO `slangwords` VALUES (430,'tentram','tenteram',NULL,NULL);
INSERT INTO `slangwords` VALUES (431,'terimakasih','terimakasih',NULL,NULL);
INSERT INTO `slangwords` VALUES (432,'terlantar','telantar',NULL,NULL);
INSERT INTO `slangwords` VALUES (433,'test','tes',NULL,NULL);
INSERT INTO `slangwords` VALUES (434,'theater','teater',NULL,NULL);
INSERT INTO `slangwords` VALUES (435,'theologi','teologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (436,'thesis','tesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (437,'ticket','tiket',NULL,NULL);
INSERT INTO `slangwords` VALUES (438,'timun','mentimun',NULL,NULL);
INSERT INTO `slangwords` VALUES (439,'ketimun','mentimun',NULL,NULL);
INSERT INTO `slangwords` VALUES (440,'tips','tip',NULL,NULL);
INSERT INTO `slangwords` VALUES (441,'tolerir','toleransi',NULL,NULL);
INSERT INTO `slangwords` VALUES (442,'toples','stoples',NULL,NULL);
INSERT INTO `slangwords` VALUES (443,'tour','tur',NULL,NULL);
INSERT INTO `slangwords` VALUES (444,'touris','turis',NULL,NULL);
INSERT INTO `slangwords` VALUES (445,'tournamen','turnamen',NULL,NULL);
INSERT INTO `slangwords` VALUES (446,'tournament','turnamen',NULL,NULL);
INSERT INTO `slangwords` VALUES (447,'tradisionil','tradisional',NULL,NULL);
INSERT INTO `slangwords` VALUES (448,'trophi','piala',NULL,NULL);
INSERT INTO `slangwords` VALUES (449,'tropi','piala',NULL,NULL);
INSERT INTO `slangwords` VALUES (450,'type','tipe',NULL,NULL);
INSERT INTO `slangwords` VALUES (451,'ujianulangan','ujian ulang',NULL,NULL);
INSERT INTO `slangwords` VALUES (452,'ultra modern','ultramodern',NULL,NULL);
INSERT INTO `slangwords` VALUES (453,'urin','urine',NULL,NULL);
INSERT INTO `slangwords` VALUES (454,'ustadz','ustaz',NULL,NULL);
INSERT INTO `slangwords` VALUES (455,'valentin','valentine',NULL,NULL);
INSERT INTO `slangwords` VALUES (456,'vampire','vampir',NULL,NULL);
INSERT INTO `slangwords` VALUES (457,'varitas','varietas',NULL,NULL);
INSERT INTO `slangwords` VALUES (458,'vegetarian','vegetaris',NULL,NULL);
INSERT INTO `slangwords` VALUES (459,'vermaks','vermak',NULL,NULL);
INSERT INTO `slangwords` VALUES (460,'vignet','vinyet',NULL,NULL);
INSERT INTO `slangwords` VALUES (461,'villa','vila',NULL,NULL);
INSERT INTO `slangwords` VALUES (462,'yudikatif','judikatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (463,'yudisial','judisial',NULL,NULL);
INSERT INTO `slangwords` VALUES (464,'yudo','judo',NULL,NULL);
INSERT INTO `slangwords` VALUES (465,'yunior','junior',NULL,NULL);
INSERT INTO `slangwords` VALUES (466,'yurisdiksi','jurisdiksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (467,'zahir','lahir',NULL,NULL);
INSERT INTO `slangwords` VALUES (468,'zohir','lahir',NULL,NULL);
INSERT INTO `slangwords` VALUES (469,'dhohir','lahir',NULL,NULL);
INSERT INTO `slangwords` VALUES (470,'zam-zam','zamzam',NULL,NULL);
INSERT INTO `slangwords` VALUES (471,'zig-zag','zigzag',NULL,NULL);
INSERT INTO `slangwords` VALUES (472,'zinah','zina',NULL,NULL);
INSERT INTO `slangwords` VALUES (473,'jina','zina',NULL,NULL);
INSERT INTO `slangwords` VALUES (474,'zygot','zigot',NULL,NULL);
INSERT INTO `slangwords` VALUES (475,'zygote','zigot',NULL,NULL);
INSERT INTO `slangwords` VALUES (476,'akte','akta',NULL,NULL);
INSERT INTO `slangwords` VALUES (477,'aktip','aktif',NULL,NULL);
INSERT INTO `slangwords` VALUES (478,'aktifitas','aktivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (479,'amandemen','amendemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (480,'handal','andal',NULL,NULL);
INSERT INTO `slangwords` VALUES (481,'analisa','analisis',NULL,NULL);
INSERT INTO `slangwords` VALUES (482,'antri','antre',NULL,NULL);
INSERT INTO `slangwords` VALUES (483,'azas','asas',NULL,NULL);
INSERT INTO `slangwords` VALUES (484,'apek','apak',NULL,NULL);
INSERT INTO `slangwords` VALUES (485,'apotik','apotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (486,'aritmatika','aritmetika',NULL,NULL);
INSERT INTO `slangwords` VALUES (487,'atlit','atlet',NULL,NULL);
INSERT INTO `slangwords` VALUES (488,'atmosfir','atmosfer',NULL,NULL);
INSERT INTO `slangwords` VALUES (489,'cabe','cabai',NULL,NULL);
INSERT INTO `slangwords` VALUES (490,'cemilan','camilan',NULL,NULL);
INSERT INTO `slangwords` VALUES (491,'cendikia','cendekia',NULL,NULL);
INSERT INTO `slangwords` VALUES (492,'cinderamata','cenderamata',NULL,NULL);
INSERT INTO `slangwords` VALUES (493,'detil','detail',NULL,NULL);
INSERT INTO `slangwords` VALUES (494,'difinisi','definisi',NULL,NULL);
INSERT INTO `slangwords` VALUES (495,'diagnosa','diagnosis',NULL,NULL);
INSERT INTO `slangwords` VALUES (496,'hembus','embus',NULL,NULL);
INSERT INTO `slangwords` VALUES (497,'extra','ekstra',NULL,NULL);
INSERT INTO `slangwords` VALUES (498,'ekstrim','ekstrem',NULL,NULL);
INSERT INTO `slangwords` VALUES (499,'esei','esai',NULL,NULL);
INSERT INTO `slangwords` VALUES (500,'pebruari','februari',NULL,NULL);
INSERT INTO `slangwords` VALUES (501,'pondasi','fondasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (502,'formil','formal',NULL,NULL);
INSERT INTO `slangwords` VALUES (503,'frase','frasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (504,'frekwensi','frekuensi',NULL,NULL);
INSERT INTO `slangwords` VALUES (505,'gisi','gizi',NULL,NULL);
INSERT INTO `slangwords` VALUES (506,'hapal','hafal',NULL,NULL);
INSERT INTO `slangwords` VALUES (507,'hakekat','hakikat',NULL,NULL);
INSERT INTO `slangwords` VALUES (508,'hipotesa','hipotesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (509,'hirarki','hierarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (510,'ijasah','ijazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (511,'ijin','izin',NULL,NULL);
INSERT INTO `slangwords` VALUES (512,'himbau','imbau',NULL,NULL);
INSERT INTO `slangwords` VALUES (513,'hisap','isap',NULL,NULL);
INSERT INTO `slangwords` VALUES (514,'isteri','istri',NULL,NULL);
INSERT INTO `slangwords` VALUES (515,'jadual','jadwal',NULL,NULL);
INSERT INTO `slangwords` VALUES (516,'jenasah','jenazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (517,'jendral','jenderal',NULL,NULL);
INSERT INTO `slangwords` VALUES (518,'justeru','justru',NULL,NULL);
INSERT INTO `slangwords` VALUES (519,'kafeteria','kafetaria',NULL,NULL);
INSERT INTO `slangwords` VALUES (520,'kalendar','kalender',NULL,NULL);
INSERT INTO `slangwords` VALUES (521,'karir','karier',NULL,NULL);
INSERT INTO `slangwords` VALUES (522,'ketapel','katapel',NULL,NULL);
INSERT INTO `slangwords` VALUES (523,'katagori','kategori',NULL,NULL);
INSERT INTO `slangwords` VALUES (524,'kadaluwarsa','kedaluwarsa',NULL,NULL);
INSERT INTO `slangwords` VALUES (525,'kenderaan','kendaraan',NULL,NULL);
INSERT INTO `slangwords` VALUES (526,'komplit','komplet',NULL,NULL);
INSERT INTO `slangwords` VALUES (527,'konperensi','konferensi',NULL,NULL);
INSERT INTO `slangwords` VALUES (528,'konggres','kongres',NULL,NULL);
INSERT INTO `slangwords` VALUES (529,'kongkrit','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (530,'kreatifitas','kreativitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (531,'kwalifikasi','kualifikasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (532,'kwalitatif','kualitatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (533,'kwantitatif','kuantitatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (534,'kwalitas','kualitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (535,'kwitansi','kuitansi',NULL,NULL);
INSERT INTO `slangwords` VALUES (536,'lobang','lubang',NULL,NULL);
INSERT INTO `slangwords` VALUES (537,'mahluk','makhluk',NULL,NULL);
INSERT INTO `slangwords` VALUES (538,'menejemen','manajemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (539,'mesjid','masjid',NULL,NULL);
INSERT INTO `slangwords` VALUES (540,'merk','merek',NULL,NULL);
INSERT INTO `slangwords` VALUES (541,'materai','meterai',NULL,NULL);
INSERT INTO `slangwords` VALUES (542,'meterei','meterai',NULL,NULL);
INSERT INTO `slangwords` VALUES (543,'metoda','metode',NULL,NULL);
INSERT INTO `slangwords` VALUES (544,'milyar','miliar',NULL,NULL);
INSERT INTO `slangwords` VALUES (545,'missi','misi',NULL,NULL);
INSERT INTO `slangwords` VALUES (546,'moderen','modern',NULL,NULL);
INSERT INTO `slangwords` VALUES (547,'mubadir','mubazir',NULL,NULL);
INSERT INTO `slangwords` VALUES (548,'mulya','mulia',NULL,NULL);
INSERT INTO `slangwords` VALUES (549,'pungkir','mungkir',NULL,NULL);
INSERT INTO `slangwords` VALUES (550,'nafas','napas',NULL,NULL);
INSERT INTO `slangwords` VALUES (551,'nara','narasumber',NULL,NULL);
INSERT INTO `slangwords` VALUES (552,'nasehat','nasihat',NULL,NULL);
INSERT INTO `slangwords` VALUES (553,'obyek','objek',NULL,NULL);
INSERT INTO `slangwords` VALUES (554,'obyektif','objektif',NULL,NULL);
INSERT INTO `slangwords` VALUES (555,'faham','paham',NULL,NULL);
INSERT INTO `slangwords` VALUES (556,'parlamen','parlemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (557,'pasport','paspor',NULL,NULL);
INSERT INTO `slangwords` VALUES (558,'perduli','peduli',NULL,NULL);
INSERT INTO `slangwords` VALUES (559,'fikir','pikir',NULL,NULL);
INSERT INTO `slangwords` VALUES (560,'praktek','praktik',NULL,NULL);
INSERT INTO `slangwords` VALUES (561,'propinsi','provinsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (562,'rebo','rabu',NULL,NULL);
INSERT INTO `slangwords` VALUES (563,'resiko','risiko',NULL,NULL);
INSERT INTO `slangwords` VALUES (564,'syah','sah',NULL,NULL);
INSERT INTO `slangwords` VALUES (565,'senggama','sanggama',NULL,NULL);
INSERT INTO `slangwords` VALUES (566,'sekedar','sekadar',NULL,NULL);
INSERT INTO `slangwords` VALUES (567,'sekular','sekuler',NULL,NULL);
INSERT INTO `slangwords` VALUES (568,'selular','seluler',NULL,NULL);
INSERT INTO `slangwords` VALUES (569,'semedi','semadi',NULL,NULL);
INSERT INTO `slangwords` VALUES (570,'central','sentral',NULL,NULL);
INSERT INTO `slangwords` VALUES (571,'seprei','seprai',NULL,NULL);
INSERT INTO `slangwords` VALUES (572,'silahkan','silakan',NULL,NULL);
INSERT INTO `slangwords` VALUES (573,'sirkular','sirkuler',NULL,NULL);
INSERT INTO `slangwords` VALUES (574,'sistim','sistem',NULL,NULL);
INSERT INTO `slangwords` VALUES (575,'seksama','saksama',NULL,NULL);
INSERT INTO `slangwords` VALUES (576,'subyek','subjek',NULL,NULL);
INSERT INTO `slangwords` VALUES (577,'subyektif','subjektif',NULL,NULL);
INSERT INTO `slangwords` VALUES (578,'sorga','surga',NULL,NULL);
INSERT INTO `slangwords` VALUES (579,'survai','survei',NULL,NULL);
INSERT INTO `slangwords` VALUES (580,'survey','survei',NULL,NULL);
INSERT INTO `slangwords` VALUES (581,'nampak','tampak',NULL,NULL);
INSERT INTO `slangwords` VALUES (582,'tauladan','teladan',NULL,NULL);
INSERT INTO `slangwords` VALUES (583,'tehnik','teknik',NULL,NULL);
INSERT INTO `slangwords` VALUES (584,'tehnologi','teknologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (585,'terlanjur','telanjur',NULL,NULL);
INSERT INTO `slangwords` VALUES (586,'terlantar','telantar',NULL,NULL);
INSERT INTO `slangwords` VALUES (587,'trampil','terampil',NULL,NULL);
INSERT INTO `slangwords` VALUES (588,'villa','vila',NULL,NULL);
INSERT INTO `slangwords` VALUES (589,'waqaf','wakaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (590,'ujud','wujud',NULL,NULL);
INSERT INTO `slangwords` VALUES (591,'yudikatip','yudikatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (592,'rubah','ubah',NULL,NULL);
INSERT INTO `slangwords` VALUES (593,'jaman','zaman',NULL,NULL);
INSERT INTO `slangwords` VALUES (594,'alfa','alpa',NULL,NULL);
INSERT INTO `slangwords` VALUES (595,'bae','baik',NULL,NULL);
INSERT INTO `slangwords` VALUES (596,'bales','balas',NULL,NULL);
INSERT INTO `slangwords` VALUES (597,'belom','belum',NULL,NULL);
INSERT INTO `slangwords` VALUES (598,'capek','capai',NULL,NULL);
INSERT INTO `slangwords` VALUES (599,'dalem','dalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (600,'dapet','dapat',NULL,NULL);
INSERT INTO `slangwords` VALUES (601,'disyahkan','disahkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (602,'febuari','februari',NULL,NULL);
INSERT INTO `slangwords` VALUES (603,'ilang','hilang',NULL,NULL);
INSERT INTO `slangwords` VALUES (604,'iklas','ikhlas',NULL,NULL);
INSERT INTO `slangwords` VALUES (605,'inget','ingat',NULL,NULL);
INSERT INTO `slangwords` VALUES (606,'itikat','itikad',NULL,NULL);
INSERT INTO `slangwords` VALUES (607,'jumaat','jumat',NULL,NULL);
INSERT INTO `slangwords` VALUES (608,'karna','karena',NULL,NULL);
INSERT INTO `slangwords` VALUES (609,'kasir','kasier',NULL,NULL);
INSERT INTO `slangwords` VALUES (610,'kharisma','karisma',NULL,NULL);
INSERT INTO `slangwords` VALUES (611,'kapada','kepada',NULL,NULL);
INSERT INTO `slangwords` VALUES (612,'kerab','kerap',NULL,NULL);
INSERT INTO `slangwords` VALUES (613,'kaedah','kaidah',NULL,NULL);
INSERT INTO `slangwords` VALUES (614,'katulistiwa','khatulistiwa',NULL,NULL);
INSERT INTO `slangwords` VALUES (615,'kawatir','khawatir',NULL,NULL);
INSERT INTO `slangwords` VALUES (616,'konkrit','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (617,'kwadrat','kuadrat',NULL,NULL);
INSERT INTO `slangwords` VALUES (618,'kwantum','kuantum',NULL,NULL);
INSERT INTO `slangwords` VALUES (619,'kuiz','kuis',NULL,NULL);
INSERT INTO `slangwords` VALUES (620,'lajim','lazim',NULL,NULL);
INSERT INTO `slangwords` VALUES (621,'lusin','losin',NULL,NULL);
INSERT INTO `slangwords` VALUES (622,'maap','maaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (623,'macem','macam',NULL,NULL);
INSERT INTO `slangwords` VALUES (624,'males','malas',NULL,NULL);
INSERT INTO `slangwords` VALUES (625,'manpaat','manfaat',NULL,NULL);
INSERT INTO `slangwords` VALUES (626,'nomer','nomor',NULL,NULL);
INSERT INTO `slangwords` VALUES (627,'matere','materai',NULL,NULL);
INSERT INTO `slangwords` VALUES (628,'mengenyampingkan','mengesampingkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (629,'merubah','mengubah',NULL,NULL);
INSERT INTO `slangwords` VALUES (630,'padet','padat',NULL,NULL);
INSERT INTO `slangwords` VALUES (631,'langganan','pelanggan',NULL,NULL);
INSERT INTO `slangwords` VALUES (632,'pinsil','pensil',NULL,NULL);
INSERT INTO `slangwords` VALUES (633,'pertanggungjawab','pertanggung jawaban',NULL,NULL);
INSERT INTO `slangwords` VALUES (634,'fihak','pihak',NULL,NULL);
INSERT INTO `slangwords` VALUES (635,'popular','populer',NULL,NULL);
INSERT INTO `slangwords` VALUES (636,'rapet','rapat',NULL,NULL);
INSERT INTO `slangwords` VALUES (637,'ampe','sampai',NULL,NULL);
INSERT INTO `slangwords` VALUES (638,'selese','selesai',NULL,NULL);
INSERT INTO `slangwords` VALUES (639,'kayak','seperti',NULL,NULL);
INSERT INTO `slangwords` VALUES (640,'action','aksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (641,'anarkhi','anarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (642,'anggauta','anggota',NULL,NULL);
INSERT INTO `slangwords` VALUES (643,'biosfir','biosfer',NULL,NULL);
INSERT INTO `slangwords` VALUES (644,'cepet','cepat',NULL,NULL);
INSERT INTO `slangwords` VALUES (645,'debet','debit',NULL,NULL);
INSERT INTO `slangwords` VALUES (646,'defaluasi','devaluasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (647,'do\'a','doa',NULL,NULL);
INSERT INTO `slangwords` VALUES (648,'diem','diam',NULL,NULL);
INSERT INTO `slangwords` VALUES (649,'daptar','daftar',NULL,NULL);
INSERT INTO `slangwords` VALUES (650,'dipersilahkan','dipersilakan',NULL,NULL);
INSERT INTO `slangwords` VALUES (651,'ekwivalen','ekuivalen',NULL,NULL);
INSERT INTO `slangwords` VALUES (652,'elit','elite',NULL,NULL);
INSERT INTO `slangwords` VALUES (653,'familiar','familier',NULL,NULL);
INSERT INTO `slangwords` VALUES (654,'glukosa','glucose',NULL,NULL);
INSERT INTO `slangwords` VALUES (655,'group','grup',NULL,NULL);
INSERT INTO `slangwords` VALUES (656,'genteng','genting',NULL,NULL);
INSERT INTO `slangwords` VALUES (657,'gubug','gubuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (658,'hektar','hectare',NULL,NULL);
INSERT INTO `slangwords` VALUES (659,'hetrogen','heterogen',NULL,NULL);
INSERT INTO `slangwords` VALUES (660,'hipotik','hipotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (661,'hirarkhi','hierarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (662,'cuma','hanya',NULL,NULL);
INSERT INTO `slangwords` VALUES (663,'abis','habis',NULL,NULL);
INSERT INTO `slangwords` VALUES (664,'idiologi','ideologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (665,'ihlas','ikhlas',NULL,NULL);
INSERT INTO `slangwords` VALUES (666,'interograsi','interogasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (667,'interospeksi','introspeksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (668,'intrupsi','interupsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (669,'institute','institut',NULL,NULL);
INSERT INTO `slangwords` VALUES (670,'kalo','kalau',NULL,NULL);
INSERT INTO `slangwords` VALUES (671,'kwantitas','kuantitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (672,'kwota','kuota',NULL,NULL);
INSERT INTO `slangwords` VALUES (673,'kridit','kredit',NULL,NULL);
INSERT INTO `slangwords` VALUES (674,'linier','linear',NULL,NULL);
INSERT INTO `slangwords` VALUES (675,'managemen','manajemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (676,'missal','masal',NULL,NULL);
INSERT INTO `slangwords` VALUES (677,'missal','misal',NULL,NULL);
INSERT INTO `slangwords` VALUES (678,'massal','masal',NULL,NULL);
INSERT INTO `slangwords` VALUES (679,'menejer','manajer',NULL,NULL);
INSERT INTO `slangwords` VALUES (680,'monarkhi','monarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (681,'moril','moral',NULL,NULL);
INSERT INTO `slangwords` VALUES (682,'netralisir','netralisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (683,'omset','omzet',NULL,NULL);
INSERT INTO `slangwords` VALUES (684,'pengreditan','pengkreditan',NULL,NULL);
INSERT INTO `slangwords` VALUES (685,'tekhnologi','teknologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (686,'university','universitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (687,'varitas','varietas',NULL,NULL);
INSERT INTO `slangwords` VALUES (688,'ada kalanya','adakalanya',NULL,NULL);
INSERT INTO `slangwords` VALUES (689,'apa bila','apabila',NULL,NULL);
INSERT INTO `slangwords` VALUES (690,'bagai mana','bagaimana',NULL,NULL);
INSERT INTO `slangwords` VALUES (691,'barang kali','barangkali',NULL,NULL);
INSERT INTO `slangwords` VALUES (692,'bila mana','bilamana',NULL,NULL);
INSERT INTO `slangwords` VALUES (693,'bea siswa','beasiswa',NULL,NULL);
INSERT INTO `slangwords` VALUES (694,'bela sungkawa','belasungkawa',NULL,NULL);
INSERT INTO `slangwords` VALUES (695,'bumi putra','bumiputra',NULL,NULL);
INSERT INTO `slangwords` VALUES (696,'dari pada','daripada',NULL,NULL);
INSERT INTO `slangwords` VALUES (697,'darma bakti','darmabakti',NULL,NULL);
INSERT INTO `slangwords` VALUES (698,'darma siswa','darmasiswa',NULL,NULL);
INSERT INTO `slangwords` VALUES (699,'duka cita','dukacita',NULL,NULL);
INSERT INTO `slangwords` VALUES (700,'hulu balang','hulubalang',NULL,NULL);
INSERT INTO `slangwords` VALUES (701,'kaca mata','kacamata',NULL,NULL);
INSERT INTO `slangwords` VALUES (702,'kasat mata','kasatmata',NULL,NULL);
INSERT INTO `slangwords` VALUES (703,'ke pada','kepada',NULL,NULL);
INSERT INTO `slangwords` VALUES (704,'kerata basa','keratabasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (705,'kosa kata','kosakata',NULL,NULL);
INSERT INTO `slangwords` VALUES (706,'loka karya','lokakarya',NULL,NULL);
INSERT INTO `slangwords` VALUES (707,'mana kala','manakala',NULL,NULL);
INSERT INTO `slangwords` VALUES (708,'mana suka','manasuka',NULL,NULL);
INSERT INTO `slangwords` VALUES (709,'mangku bumi','mangkubumi',NULL,NULL);
INSERT INTO `slangwords` VALUES (710,'mara bahaya','marabahaya',NULL,NULL);
INSERT INTO `slangwords` VALUES (711,'mata hari','matahari',NULL,NULL);
INSERT INTO `slangwords` VALUES (712,'olah raga','olahraga',NULL,NULL);
INSERT INTO `slangwords` VALUES (713,'pada hal','padahal',NULL,NULL);
INSERT INTO `slangwords` VALUES (714,'parama sastra','paramasastra',NULL,NULL);
INSERT INTO `slangwords` VALUES (715,'puspa warna','puspawarna',NULL,NULL);
INSERT INTO `slangwords` VALUES (716,'radio aktif','radioaktif',NULL,NULL);
INSERT INTO `slangwords` VALUES (717,'sastra marga','sastramarga',NULL,NULL);
INSERT INTO `slangwords` VALUES (718,'sapu tangan','saputangan',NULL,NULL);
INSERT INTO `slangwords` VALUES (719,'sari pati','saripati',NULL,NULL);
INSERT INTO `slangwords` VALUES (720,'sebagai mana','sebagaimana',NULL,NULL);
INSERT INTO `slangwords` VALUES (721,'sedia kala','sediakala',NULL,NULL);
INSERT INTO `slangwords` VALUES (722,'segitiga','segi tiga',NULL,NULL);
INSERT INTO `slangwords` VALUES (723,'silatu rahmi','silaturahmi',NULL,NULL);
INSERT INTO `slangwords` VALUES (724,'suka cita','sukacita',NULL,NULL);
INSERT INTO `slangwords` VALUES (725,'suka rela','sukarela',NULL,NULL);
INSERT INTO `slangwords` VALUES (726,'suka ria','sukaria',NULL,NULL);
INSERT INTO `slangwords` VALUES (727,'syah bandar','syahbandar',NULL,NULL);
INSERT INTO `slangwords` VALUES (728,'titi mangsa','titimangsa',NULL,NULL);
INSERT INTO `slangwords` VALUES (729,'walikota','wali kota',NULL,NULL);
INSERT INTO `slangwords` VALUES (730,'eka bahasa','ekabahasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (731,'dwi bahasa','dwibahasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (732,'tri darma','tridarma',NULL,NULL);
INSERT INTO `slangwords` VALUES (733,'tri tunggal','tritunggal',NULL,NULL);
INSERT INTO `slangwords` VALUES (734,'catur warga','caturwarga',NULL,NULL);
INSERT INTO `slangwords` VALUES (735,'catur wulan','caturwulan',NULL,NULL);
INSERT INTO `slangwords` VALUES (736,'panca indra','pancaindra',NULL,NULL);
INSERT INTO `slangwords` VALUES (737,'panca sila','pancasila',NULL,NULL);
INSERT INTO `slangwords` VALUES (738,'sapta krida','saptakrida',NULL,NULL);
INSERT INTO `slangwords` VALUES (739,'sapta pesona','saptapesona',NULL,NULL);
INSERT INTO `slangwords` VALUES (740,'dasa titah','dasatitah',NULL,NULL);
INSERT INTO `slangwords` VALUES (741,'dasa warsa','dasawarsa',NULL,NULL);
INSERT INTO `slangwords` VALUES (742,'kilo gram','kilogram',NULL,NULL);
INSERT INTO `slangwords` VALUES (743,'mega watt','megawatt',NULL,NULL);
INSERT INTO `slangwords` VALUES (744,'tera bita','terabita',NULL,NULL);
INSERT INTO `slangwords` VALUES (745,'giga ohm','gigaohm',NULL,NULL);
INSERT INTO `slangwords` VALUES (746,'senti meter','sentimeter',NULL,NULL);
INSERT INTO `slangwords` VALUES (747,'mikro organisme','mikroorganisme',NULL,NULL);
INSERT INTO `slangwords` VALUES (748,'kilo meter','kilometer',NULL,NULL);
INSERT INTO `slangwords` VALUES (749,'a moral','amoral',NULL,NULL);
INSERT INTO `slangwords` VALUES (750,'a susila','asusila',NULL,NULL);
INSERT INTO `slangwords` VALUES (751,'antar negara','antarnegara',NULL,NULL);
INSERT INTO `slangwords` VALUES (752,'antar warga','antarwarga',NULL,NULL);
INSERT INTO `slangwords` VALUES (753,'ekstra kurikuler','ekstrakurikuler',NULL,NULL);
INSERT INTO `slangwords` VALUES (754,'kontra revolusi','kontrarevolusi',NULL,NULL);
INSERT INTO `slangwords` VALUES (755,'maha agung','mahaagung',NULL,NULL);
INSERT INTO `slangwords` VALUES (756,'mahapengasih1','maha pengasih',NULL,NULL);
INSERT INTO `slangwords` VALUES (757,'non blok','nonblok',NULL,NULL);
INSERT INTO `slangwords` VALUES (758,'non indonesia2','non-indonesia',NULL,NULL);
INSERT INTO `slangwords` VALUES (759,'peri laku','perilaku',NULL,NULL);
INSERT INTO `slangwords` VALUES (760,'perikeadilan1','peri keadilan',NULL,NULL);
INSERT INTO `slangwords` VALUES (761,'pasca panen','pascapanen',NULL,NULL);
INSERT INTO `slangwords` VALUES (762,'semi profesional','semiprofesional',NULL,NULL);
INSERT INTO `slangwords` VALUES (763,'sub bagian','subbagian',NULL,NULL);
INSERT INTO `slangwords` VALUES (764,'super sibuk','supersibuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (765,'tuna karya','tunakarya',NULL,NULL);
INSERT INTO `slangwords` VALUES (766,'ultra modern','ultramodern',NULL,NULL);
INSERT INTO `slangwords` VALUES (767,'malpraktik','malapraktik',NULL,NULL);
INSERT INTO `slangwords` VALUES (768,'malfungsi','malafungsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (769,'malserap','malaserap',NULL,NULL);
INSERT INTO `slangwords` VALUES (770,'maladaptasi','malaadaptasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (771,'malsuai','malasuai',NULL,NULL);
INSERT INTO `slangwords` VALUES (772,'maldistribusi','maladistribusi',NULL,NULL);
INSERT INTO `slangwords` VALUES (773,'malgizi','malagizi',NULL,NULL);
INSERT INTO `slangwords` VALUES (774,'malsikap','malasikap',NULL,NULL);
INSERT INTO `slangwords` VALUES (775,'andai pun','andaipun',NULL,NULL);
INSERT INTO `slangwords` VALUES (776,'atau pun','ataupun',NULL,NULL);
INSERT INTO `slangwords` VALUES (777,'bagaimana pun','bagaimanapun',NULL,NULL);
INSERT INTO `slangwords` VALUES (778,'biar pun','biarpun',NULL,NULL);
INSERT INTO `slangwords` VALUES (779,'kalau pun','kalaupun',NULL,NULL);
INSERT INTO `slangwords` VALUES (780,'kendati pun','kendatipun',NULL,NULL);
INSERT INTO `slangwords` VALUES (781,'meski pun','meskipun',NULL,NULL);
INSERT INTO `slangwords` VALUES (782,'sungguh pun','sungguhpun',NULL,NULL);
INSERT INTO `slangwords` VALUES (783,'walau pun','walaupun',NULL,NULL);
INSERT INTO `slangwords` VALUES (784,'hindia-belanda','hindia belanda',NULL,NULL);
INSERT INTO `slangwords` VALUES (785,'asal-usul','asal usul',NULL,NULL);
INSERT INTO `slangwords` VALUES (786,'diantara','di antara',NULL,NULL);
INSERT INTO `slangwords` VALUES (787,'diakhir','di akhir',NULL,NULL);
INSERT INTO `slangwords` VALUES (788,'diatas','di atas',NULL,NULL);
INSERT INTO `slangwords` VALUES (789,'diawal','di awal',NULL,NULL);
INSERT INTO `slangwords` VALUES (790,'dibagian','di bagian',NULL,NULL);
INSERT INTO `slangwords` VALUES (791,'dibawah','di bawah',NULL,NULL);
INSERT INTO `slangwords` VALUES (792,'dibelakang','di belakang',NULL,NULL);
INSERT INTO `slangwords` VALUES (793,'didalam','di dalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (794,'didekat','di dekat',NULL,NULL);
INSERT INTO `slangwords` VALUES (795,'didepan','di depan',NULL,NULL);
INSERT INTO `slangwords` VALUES (796,'dihadapan','di hadapan',NULL,NULL);
INSERT INTO `slangwords` VALUES (797,'dijalan','di jalan',NULL,NULL);
INSERT INTO `slangwords` VALUES (798,'dikanan','di kanan',NULL,NULL);
INSERT INTO `slangwords` VALUES (799,'dikiri','di kiri',NULL,NULL);
INSERT INTO `slangwords` VALUES (800,'diluar','di luar',NULL,NULL);
INSERT INTO `slangwords` VALUES (801,'dimana','di mana',NULL,NULL);
INSERT INTO `slangwords` VALUES (802,'dimuka','di muka',NULL,NULL);
INSERT INTO `slangwords` VALUES (803,'dipusat','di pusat',NULL,NULL);
INSERT INTO `slangwords` VALUES (804,'dirumah','di rumah',NULL,NULL);
INSERT INTO `slangwords` VALUES (805,'disamping','di samping',NULL,NULL);
INSERT INTO `slangwords` VALUES (806,'disaat','di saat',NULL,NULL);
INSERT INTO `slangwords` VALUES (807,'disana','di sana',NULL,NULL);
INSERT INTO `slangwords` VALUES (808,'disebelah','di sebelah',NULL,NULL);
INSERT INTO `slangwords` VALUES (809,'diseberang','di seberang',NULL,NULL);
INSERT INTO `slangwords` VALUES (810,'disekeliling','di sekeliling',NULL,NULL);
INSERT INTO `slangwords` VALUES (811,'disekitar','di sekitar',NULL,NULL);
INSERT INTO `slangwords` VALUES (812,'diseluruh','di seluruh',NULL,NULL);
INSERT INTO `slangwords` VALUES (813,'disini','di sini',NULL,NULL);
INSERT INTO `slangwords` VALUES (814,'disisi','di sisi',NULL,NULL);
INSERT INTO `slangwords` VALUES (815,'disitu','di situ',NULL,NULL);
INSERT INTO `slangwords` VALUES (816,'ditanah','di tanah',NULL,NULL);
INSERT INTO `slangwords` VALUES (817,'ditempat','di tempat',NULL,NULL);
INSERT INTO `slangwords` VALUES (818,'ditengah','di tengah',NULL,NULL);
INSERT INTO `slangwords` VALUES (819,'ditengah-tengah','di tengah-tengah',NULL,NULL);
INSERT INTO `slangwords` VALUES (820,'ditepi','di tepi',NULL,NULL);
INSERT INTO `slangwords` VALUES (821,'ditiap','di tiap',NULL,NULL);
INSERT INTO `slangwords` VALUES (822,'ditiap-tiap','di tiap-tiap',NULL,NULL);
INSERT INTO `slangwords` VALUES (823,'keatas','ke atas',NULL,NULL);
INSERT INTO `slangwords` VALUES (824,'kebawah','ke bawah',NULL,NULL);
INSERT INTO `slangwords` VALUES (825,'kebelakang','ke belakang',NULL,NULL);
INSERT INTO `slangwords` VALUES (826,'kedalam','ke dalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (827,'kedepan','ke depan',NULL,NULL);
INSERT INTO `slangwords` VALUES (828,'kehadapan','ke hadapan',NULL,NULL);
INSERT INTO `slangwords` VALUES (829,'kekanan','ke kanan',NULL,NULL);
INSERT INTO `slangwords` VALUES (830,'kekiri','ke kiri',NULL,NULL);
INSERT INTO `slangwords` VALUES (831,'kemana','ke mana',NULL,NULL);
INSERT INTO `slangwords` VALUES (832,'kesana','ke sana',NULL,NULL);
INSERT INTO `slangwords` VALUES (833,'kesamping','ke samping',NULL,NULL);
INSERT INTO `slangwords` VALUES (834,'ketempat','ke tempat',NULL,NULL);
INSERT INTO `slangwords` VALUES (835,'aktuil','aktual',NULL,NULL);
INSERT INTO `slangwords` VALUES (836,'trotoir','trotoar',NULL,NULL);
INSERT INTO `slangwords` VALUES (837,'komersiil','komersial',NULL,NULL);
INSERT INTO `slangwords` VALUES (838,'komersil','komersial',NULL,NULL);
INSERT INTO `slangwords` VALUES (839,'tradisionil','tradisional',NULL,NULL);
INSERT INTO `slangwords` VALUES (840,'orisinil','orisinal',NULL,NULL);
INSERT INTO `slangwords` VALUES (841,'orijinil','orisinal',NULL,NULL);
INSERT INTO `slangwords` VALUES (842,'orijinal','orisinal',NULL,NULL);
INSERT INTO `slangwords` VALUES (843,'riil','real',NULL,NULL);
INSERT INTO `slangwords` VALUES (844,'afdol','afdal',NULL,NULL);
INSERT INTO `slangwords` VALUES (845,'cidera','cedera',NULL,NULL);
INSERT INTO `slangwords` VALUES (846,'dekrit2','dekret',NULL,NULL);
INSERT INTO `slangwords` VALUES (847,'disain','desain',NULL,NULL);
INSERT INTO `slangwords` VALUES (848,'diskripsi','deskripsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (849,'diskotik','diskotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (850,'eksim','eksem',NULL,NULL);
INSERT INTO `slangwords` VALUES (851,'exim','eksem',NULL,NULL);
INSERT INTO `slangwords` VALUES (852,'faidah','faedah',NULL,NULL);
INSERT INTO `slangwords` VALUES (853,'kongkret','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (854,'musium','museum',NULL,NULL);
INSERT INTO `slangwords` VALUES (855,'pinalti','penalti',NULL,NULL);
INSERT INTO `slangwords` VALUES (856,'piranti','peranti',NULL,NULL);
INSERT INTO `slangwords` VALUES (857,'personil','personel',NULL,NULL);
INSERT INTO `slangwords` VALUES (858,'teoritis','teoretis',NULL,NULL);
INSERT INTO `slangwords` VALUES (859,'vidio','video',NULL,NULL);
INSERT INTO `slangwords` VALUES (860,'cengkeh','cengkih',NULL,NULL);
INSERT INTO `slangwords` VALUES (861,'desertasi','disertasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (862,'intelejen','intelijen',NULL,NULL);
INSERT INTO `slangwords` VALUES (863,'kempes','kempis',NULL,NULL);
INSERT INTO `slangwords` VALUES (864,'ledeng','leding',NULL,NULL);
INSERT INTO `slangwords` VALUES (865,'retsleting','ritsleting',NULL,NULL);
INSERT INTO `slangwords` VALUES (866,'senen','senin',NULL,NULL);
INSERT INTO `slangwords` VALUES (867,'amuba','ameba',NULL,NULL);
INSERT INTO `slangwords` VALUES (868,'punggawa','penggawa',NULL,NULL);
INSERT INTO `slangwords` VALUES (869,'surban','serban',NULL,NULL);
INSERT INTO `slangwords` VALUES (870,'sorban','serban',NULL,NULL);
INSERT INTO `slangwords` VALUES (871,'agribisnis','agrobisnis',NULL,NULL);
INSERT INTO `slangwords` VALUES (872,'kantung','kantong',NULL,NULL);
INSERT INTO `slangwords` VALUES (873,'khutbah','khotbah',NULL,NULL);
INSERT INTO `slangwords` VALUES (874,'mandur','mandor',NULL,NULL);
INSERT INTO `slangwords` VALUES (875,'rubuh','roboh',NULL,NULL);
INSERT INTO `slangwords` VALUES (876,'pastur','pastor',NULL,NULL);
INSERT INTO `slangwords` VALUES (877,'supir','sopir',NULL,NULL);
INSERT INTO `slangwords` VALUES (878,'babon','babun',NULL,NULL);
INSERT INTO `slangwords` VALUES (879,'goncang','guncang',NULL,NULL);
INSERT INTO `slangwords` VALUES (880,'goa','gua',NULL,NULL);
INSERT INTO `slangwords` VALUES (881,'kaos','kaus',NULL,NULL);
INSERT INTO `slangwords` VALUES (882,'kokoh','kukuh',NULL,NULL);
INSERT INTO `slangwords` VALUES (883,'komulatif','kumulatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (884,'kolomnis','kolumnis',NULL,NULL);
INSERT INTO `slangwords` VALUES (885,'korma','kurma',NULL,NULL);
INSERT INTO `slangwords` VALUES (886,'limo','limusin',NULL,NULL);
INSERT INTO `slangwords` VALUES (887,'limosin','limusin',NULL,NULL);
INSERT INTO `slangwords` VALUES (888,'mangkok','mangkuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (889,'saos','saus',NULL,NULL);
INSERT INTO `slangwords` VALUES (890,'sop','sup',NULL,NULL);
INSERT INTO `slangwords` VALUES (891,'tegor','tegur',NULL,NULL);
INSERT INTO `slangwords` VALUES (892,'telor','telur',NULL,NULL);
INSERT INTO `slangwords` VALUES (893,'obrak-abrik','ubrak-abrik',NULL,NULL);
INSERT INTO `slangwords` VALUES (894,'konsekwensi','konsekuensi',NULL,NULL);
INSERT INTO `slangwords` VALUES (895,'kwadran','kuadran',NULL,NULL);
INSERT INTO `slangwords` VALUES (896,'kwalitet','kualitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (897,'kwartal','kuartal',NULL,NULL);
INSERT INTO `slangwords` VALUES (898,'kwintal','kuintal',NULL,NULL);
INSERT INTO `slangwords` VALUES (899,'kwatir','khawatir',NULL,NULL);
INSERT INTO `slangwords` VALUES (900,'kuatir','khawatir',NULL,NULL);
INSERT INTO `slangwords` VALUES (901,'aktiv','aktif',NULL,NULL);
INSERT INTO `slangwords` VALUES (902,'efektip','efektif',NULL,NULL);
INSERT INTO `slangwords` VALUES (903,'epektip','epektif',NULL,NULL);
INSERT INTO `slangwords` VALUES (904,'pisik','fisik',NULL,NULL);
INSERT INTO `slangwords` VALUES (905,'photo','foto',NULL,NULL);
INSERT INTO `slangwords` VALUES (906,'photokopi','fotokopi',NULL,NULL);
INSERT INTO `slangwords` VALUES (907,'insap','insaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (908,'insyaf','insaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (909,'kreatip','kreatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (910,'kreativ','kreatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (911,'napsu','nafsu',NULL,NULL);
INSERT INTO `slangwords` VALUES (912,'negatip','negatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (913,'negativ','negatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (914,'pasip','pasif',NULL,NULL);
INSERT INTO `slangwords` VALUES (915,'pasiv','pasif',NULL,NULL);
INSERT INTO `slangwords` VALUES (916,'positip','positif',NULL,NULL);
INSERT INTO `slangwords` VALUES (917,'positiv','positif',NULL,NULL);
INSERT INTO `slangwords` VALUES (918,'produktip','produktif',NULL,NULL);
INSERT INTO `slangwords` VALUES (919,'produktiv','produktif',NULL,NULL);
INSERT INTO `slangwords` VALUES (920,'sarap','saraf',NULL,NULL);
INSERT INTO `slangwords` VALUES (921,'sertipikat','sertifikat',NULL,NULL);
INSERT INTO `slangwords` VALUES (922,'tarip','tarif',NULL,NULL);
INSERT INTO `slangwords` VALUES (923,'transitip','transitif',NULL,NULL);
INSERT INTO `slangwords` VALUES (924,'transitiv','transitif',NULL,NULL);
INSERT INTO `slangwords` VALUES (925,'telefon','telepon',NULL,NULL);
INSERT INTO `slangwords` VALUES (926,'telfon','telepon',NULL,NULL);
INSERT INTO `slangwords` VALUES (927,'telpon','telepon',NULL,NULL);
INSERT INTO `slangwords` VALUES (928,'tilpon','telepon',NULL,NULL);
INSERT INTO `slangwords` VALUES (929,'vermak','permak',NULL,NULL);
INSERT INTO `slangwords` VALUES (930,'vulpen','pulpen',NULL,NULL);
INSERT INTO `slangwords` VALUES (931,'aktifis','aktivis',NULL,NULL);
INSERT INTO `slangwords` VALUES (932,'konfeksi','konveksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (933,'motifasi','motivasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (934,'nopember','november',NULL,NULL);
INSERT INTO `slangwords` VALUES (935,'babtis','baptis',NULL,NULL);
INSERT INTO `slangwords` VALUES (936,'jerembab','jerembap',NULL,NULL);
INSERT INTO `slangwords` VALUES (937,'lembab','lembap',NULL,NULL);
INSERT INTO `slangwords` VALUES (938,'sembab','sembap',NULL,NULL);
INSERT INTO `slangwords` VALUES (939,'saptu','sabtu',NULL,NULL);
INSERT INTO `slangwords` VALUES (940,'tekat','tekad',NULL,NULL);
INSERT INTO `slangwords` VALUES (941,'bejad','bejat',NULL,NULL);
INSERT INTO `slangwords` VALUES (942,'nekad','nekat',NULL,NULL);
INSERT INTO `slangwords` VALUES (943,'otoped','otopet',NULL,NULL);
INSERT INTO `slangwords` VALUES (944,'skuad','skuat',NULL,NULL);
INSERT INTO `slangwords` VALUES (945,'jenius','genius',NULL,NULL);
INSERT INTO `slangwords` VALUES (946,'marjin','margin',NULL,NULL);
INSERT INTO `slangwords` VALUES (947,'marjinal','marginal',NULL,NULL);
INSERT INTO `slangwords` VALUES (948,'projek','proyek',NULL,NULL);
INSERT INTO `slangwords` VALUES (949,'plasa','plaza',NULL,NULL);
INSERT INTO `slangwords` VALUES (950,'bathin','batin',NULL,NULL);
INSERT INTO `slangwords` VALUES (951,'katholik','katolik',NULL,NULL);
INSERT INTO `slangwords` VALUES (952,'orthografi','ortografi',NULL,NULL);
INSERT INTO `slangwords` VALUES (953,'pathogen','patogen',NULL,NULL);
INSERT INTO `slangwords` VALUES (954,'theologi','teologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (955,'rejeki','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (956,'rizki','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (957,'riski','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (958,'rizqi','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (959,'rejim','rezim',NULL,NULL);
INSERT INTO `slangwords` VALUES (960,'jamrud','zamrud',NULL,NULL);
INSERT INTO `slangwords` VALUES (961,'anugrah','anugerah',NULL,NULL);
INSERT INTO `slangwords` VALUES (962,'cendrawasih','cenderawasih',NULL,NULL);
INSERT INTO `slangwords` VALUES (963,'indra','indera',NULL,NULL);
INSERT INTO `slangwords` VALUES (964,'kripik','keripik',NULL,NULL);
INSERT INTO `slangwords` VALUES (965,'krupuk','kerupuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (966,'ksatria','kesatria',NULL,NULL);
INSERT INTO `slangwords` VALUES (967,'satria','kesatria',NULL,NULL);
INSERT INTO `slangwords` VALUES (968,'mentri','menteri',NULL,NULL);
INSERT INTO `slangwords` VALUES (969,'negri','negeri',NULL,NULL);
INSERT INTO `slangwords` VALUES (970,'prancis','perancis',NULL,NULL);
INSERT INTO `slangwords` VALUES (971,'sebrang','seberang',NULL,NULL);
INSERT INTO `slangwords` VALUES (972,'menyebrang','menyeberang',NULL,NULL);
INSERT INTO `slangwords` VALUES (973,'sumatra','sumatera',NULL,NULL);
INSERT INTO `slangwords` VALUES (974,'perajurit','prajurit',NULL,NULL);
INSERT INTO `slangwords` VALUES (975,'putera','putra',NULL,NULL);
INSERT INTO `slangwords` VALUES (976,'puteri','putri',NULL,NULL);
INSERT INTO `slangwords` VALUES (977,'samudera','samudra',NULL,NULL);
INSERT INTO `slangwords` VALUES (978,'sastera','sastra',NULL,NULL);
INSERT INTO `slangwords` VALUES (979,'sutera','sutra',NULL,NULL);
INSERT INTO `slangwords` VALUES (980,'terompet','trompet',NULL,NULL);
INSERT INTO `slangwords` VALUES (981,'iktisar','ikhtisar',NULL,NULL);
INSERT INTO `slangwords` VALUES (982,'kotbah','khotbah',NULL,NULL);
INSERT INTO `slangwords` VALUES (983,'kusyuk','khusyuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (984,'makluk','makhluk',NULL,NULL);
INSERT INTO `slangwords` VALUES (985,'mahkluk','makhluk',NULL,NULL);
INSERT INTO `slangwords` VALUES (986,'nahkoda','nakhoda',NULL,NULL);
INSERT INTO `slangwords` VALUES (987,'nakoda','nakhoda',NULL,NULL);
INSERT INTO `slangwords` VALUES (988,'tahta','takhta',NULL,NULL);
INSERT INTO `slangwords` VALUES (989,'takhyul','takhayul',NULL,NULL);
INSERT INTO `slangwords` VALUES (990,'tahyul','takhayul',NULL,NULL);
INSERT INTO `slangwords` VALUES (991,'tahayul','takhayul',NULL,NULL);
INSERT INTO `slangwords` VALUES (992,'akhli','ahli',NULL,NULL);
INSERT INTO `slangwords` VALUES (993,'rakhmat','rahmat',NULL,NULL);
INSERT INTO `slangwords` VALUES (994,'tekhnik','teknik',NULL,NULL);
INSERT INTO `slangwords` VALUES (995,'ikhwal','ihwal',NULL,NULL);
INSERT INTO `slangwords` VALUES (996,'sex','seks',NULL,NULL);
INSERT INTO `slangwords` VALUES (997,'taxi','taksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (998,'extasi','ekstasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (999,'expor','ekspor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1000,'syaraf','saraf',NULL,NULL);
INSERT INTO `slangwords` VALUES (1001,'syurga','surga',NULL,NULL);
INSERT INTO `slangwords` VALUES (1002,'mashur','masyhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1003,'masyur','masyhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1004,'mahsyur','masyhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1005,'mashyur','masyhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1006,'muadzin','muazin',NULL,NULL);
INSERT INTO `slangwords` VALUES (1007,'adzan','azan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1008,'ustadz','ustaz',NULL,NULL);
INSERT INTO `slangwords` VALUES (1009,'ustad','ustaz',NULL,NULL);
INSERT INTO `slangwords` VALUES (1010,'ustadzah','ustazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1011,'dzikir','zikir',NULL,NULL);
INSERT INTO `slangwords` VALUES (1012,'dzuhur','zuhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1013,'dhuhur','zuhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1014,'zhuhur','zuhur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1015,'sintesa','sintesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1016,'efektifitas','efektivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1017,'komuniti','komunitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1018,'produktifitas','produktivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1019,'realiti','realitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1020,'realita','realitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1021,'selebriti','selebritas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1022,'sportifitas','sportivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1023,'universiti','universitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1024,'utiliti','utilitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1025,'validiti','validitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1026,'dilokalisir','dilokalisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1027,'didramatisir','didramatisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1028,'dipolitisir','dipolitisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1029,'dinetralisir','dinetralisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1030,'dikonfrontir','dikonfrontasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1031,'mendominir','mendominasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1032,'koordinir','koordinasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1033,'proklamir','proklamasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1034,'terorganisir','terorganisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1035,'terealisir','terealisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1036,'menyintai','mencintai',NULL,NULL);
INSERT INTO `slangwords` VALUES (1037,'menyolok','mencolok',NULL,NULL);
INSERT INTO `slangwords` VALUES (1038,'contek','sontek',NULL,NULL);
INSERT INTO `slangwords` VALUES (1039,'mencontek','menyontek',NULL,NULL);
INSERT INTO `slangwords` VALUES (1040,'aksesoris','aksesori',NULL,NULL);
INSERT INTO `slangwords` VALUES (1041,'hantar','antar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1042,'panutan','anutan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1043,'atsiri','asiri',NULL,NULL);
INSERT INTO `slangwords` VALUES (1044,'bhakti','bakti',NULL,NULL);
INSERT INTO `slangwords` VALUES (1045,'china','cina',NULL,NULL);
INSERT INTO `slangwords` VALUES (1046,'dharma','darma',NULL,NULL);
INSERT INTO `slangwords` VALUES (1047,'diktaktor','diktator',NULL,NULL);
INSERT INTO `slangwords` VALUES (1048,'eksport','ekspor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1049,'hadits','hadis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1050,'hadist','hadis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1051,'harafiah','harfiah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1052,'import','impor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1053,'interprestasi','interpretasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1054,'kangker','kanker',NULL,NULL);
INSERT INTO `slangwords` VALUES (1055,'lansekap','lanskap',NULL,NULL);
INSERT INTO `slangwords` VALUES (1056,'maghrib','magrib',NULL,NULL);
INSERT INTO `slangwords` VALUES (1057,'ramadhan','ramadan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1058,'rapih','rapi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1059,'sansekerta','sanskerta',NULL,NULL);
INSERT INTO `slangwords` VALUES (1060,'sri langka','sri lanka',NULL,NULL);
INSERT INTO `slangwords` VALUES (1061,'shalat','salat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1062,'sholat','salat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1063,'solat','salat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1064,'standard','standar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1065,'standarisasi','standardisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1066,'hutang','utang',NULL,NULL);
INSERT INTO `slangwords` VALUES (1067,'zinah','zina',NULL,NULL);
INSERT INTO `slangwords` VALUES (1068,'jum\'at','jumat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1069,'la\'nat','laknat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1070,'ma\'af','maaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (1071,'mu\'jizat','mukjizat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1072,'mujizat','mukjizat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1073,'mujijat','mukjizat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1074,'ni\'mat','nikmat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1075,'raka\'at','rakaat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1076,'ta\'at','taat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1077,'amphibi','amfibi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1078,'anjlog','anjlok',NULL,NULL);
INSERT INTO `slangwords` VALUES (1079,'alpukat','avokad',NULL,NULL);
INSERT INTO `slangwords` VALUES (1080,'alpokat','avokad',NULL,NULL);
INSERT INTO `slangwords` VALUES (1081,'bolpen','pulpen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1082,'cabay','cabai',NULL,NULL);
INSERT INTO `slangwords` VALUES (1083,'ceret','cerek',NULL,NULL);
INSERT INTO `slangwords` VALUES (1084,'differensial','diferensial',NULL,NULL);
INSERT INTO `slangwords` VALUES (1085,'duren','durian',NULL,NULL);
INSERT INTO `slangwords` VALUES (1086,'faksimili','faksimile',NULL,NULL);
INSERT INTO `slangwords` VALUES (1087,'faksimil','faksimile',NULL,NULL);
INSERT INTO `slangwords` VALUES (1088,'graha','gerha',NULL,NULL);
INSERT INTO `slangwords` VALUES (1089,'goblog','goblok',NULL,NULL);
INSERT INTO `slangwords` VALUES (1090,'gombrong','gombroh',NULL,NULL);
INSERT INTO `slangwords` VALUES (1091,'horden','gorden',NULL,NULL);
INSERT INTO `slangwords` VALUES (1092,'korden','gorden',NULL,NULL);
INSERT INTO `slangwords` VALUES (1093,'imaginasi','imajinasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1094,'jerigen','jeriken',NULL,NULL);
INSERT INTO `slangwords` VALUES (1095,'jirigen','jeriken',NULL,NULL);
INSERT INTO `slangwords` VALUES (1096,'carut-marut','karut-marut',NULL,NULL);
INSERT INTO `slangwords` VALUES (1097,'mahzab','mazhab',NULL,NULL);
INSERT INTO `slangwords` VALUES (1098,'mempesona','memesona',NULL,NULL);
INSERT INTO `slangwords` VALUES (1099,'nenas','nanas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1100,'negoisasi','negosiasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1101,'automotif','otomotif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1102,'pararel','paralel',NULL,NULL);
INSERT INTO `slangwords` VALUES (1103,'paska','pasca',NULL,NULL);
INSERT INTO `slangwords` VALUES (1104,'prosen','persen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1105,'petay','petai',NULL,NULL);
INSERT INTO `slangwords` VALUES (1106,'proffesor','profesor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1107,'rame','ramai',NULL,NULL);
INSERT INTO `slangwords` VALUES (1108,'rapot','rapor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1109,'rileks','relaks',NULL,NULL);
INSERT INTO `slangwords` VALUES (1110,'rileksasi','relaksasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1111,'renumerasi','remunerasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1112,'seketaris','sekretaris',NULL,NULL);
INSERT INTO `slangwords` VALUES (1113,'sekertaris','sekretaris',NULL,NULL);
INSERT INTO `slangwords` VALUES (1114,'sensorik','sensoris',NULL,NULL);
INSERT INTO `slangwords` VALUES (1115,'sentausa','sentosa',NULL,NULL);
INSERT INTO `slangwords` VALUES (1116,'strawberi','stroberi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1117,'strawbery','stroberi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1118,'strawberry','stroberi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1119,'taqwa','takwa',NULL,NULL);
INSERT INTO `slangwords` VALUES (1120,'tauco','taoco',NULL,NULL);
INSERT INTO `slangwords` VALUES (1121,'tauge','taoge',NULL,NULL);
INSERT INTO `slangwords` VALUES (1122,'toge','taoge',NULL,NULL);
INSERT INTO `slangwords` VALUES (1123,'taubat','tobat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1124,'trilyun','triliun',NULL,NULL);
INSERT INTO `slangwords` VALUES (1125,'vissi','visi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1126,'aktifitas','aktivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1127,'apotik','apotek',NULL,NULL);
INSERT INTO `slangwords` VALUES (1128,'analisa','analisis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1129,'azas','asas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1130,'atlit','atlet',NULL,NULL);
INSERT INTO `slangwords` VALUES (1131,'atmosfir','atmosfer',NULL,NULL);
INSERT INTO `slangwords` VALUES (1132,'cinderamata','cenderamata',NULL,NULL);
INSERT INTO `slangwords` VALUES (1133,'difinisi','definisi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1134,'pebruari','februari',NULL,NULL);
INSERT INTO `slangwords` VALUES (1135,'hakekat','hakikat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1136,'hipotesa','hipotesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1137,'hirarki','hierarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (1138,'ijasah','ijazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1139,'ijin','izin',NULL,NULL);
INSERT INTO `slangwords` VALUES (1140,'jadual','jadwal',NULL,NULL);
INSERT INTO `slangwords` VALUES (1141,'jenasah','jenazah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1142,'kaedah','kaidah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1143,'karir','karier',NULL,NULL);
INSERT INTO `slangwords` VALUES (1144,'kondite','konduite',NULL,NULL);
INSERT INTO `slangwords` VALUES (1145,'konkrit','konkret',NULL,NULL);
INSERT INTO `slangwords` VALUES (1146,'konsepsionil','konsepsional',NULL,NULL);
INSERT INTO `slangwords` VALUES (1147,'kwitansi','kuitansi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1148,'lembab','lembap',NULL,NULL);
INSERT INTO `slangwords` VALUES (1149,'lobang','lubang',NULL,NULL);
INSERT INTO `slangwords` VALUES (1150,'mengobah','mengubah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1151,'merobah','merubah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1152,'menterjemahkan','menerjemahkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1153,'metoda','metode',NULL,NULL);
INSERT INTO `slangwords` VALUES (1154,'musti','mesti',NULL,NULL);
INSERT INTO `slangwords` VALUES (1155,'motip','motif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1156,'motifasi','motivasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1157,'nasehat','nasihat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1158,'nopember','november',NULL,NULL);
INSERT INTO `slangwords` VALUES (1159,'seksama','saksama',NULL,NULL);
INSERT INTO `slangwords` VALUES (1160,'rejeki','rezeki',NULL,NULL);
INSERT INTO `slangwords` VALUES (1161,'sintesa','sintesis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1162,'sistim','sistem',NULL,NULL);
INSERT INTO `slangwords` VALUES (1163,'sistimatis','sistematis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1164,'standarisasi','standardisasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1165,'sipiritual','spiritual',NULL,NULL);
INSERT INTO `slangwords` VALUES (1166,'subyektip','subjektif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1167,'sutra','sutera',NULL,NULL);
INSERT INTO `slangwords` VALUES (1168,'tarip','tarif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1169,'tapsiran','tafsiran',NULL,NULL);
INSERT INTO `slangwords` VALUES (1170,'terlentang','telentang',NULL,NULL);
INSERT INTO `slangwords` VALUES (1171,'terlanjur','telanjur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1172,'terlantar','telantar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1173,'teoritis','teoretis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1174,'tehnik','teknik',NULL,NULL);
INSERT INTO `slangwords` VALUES (1175,'trampil','terampil',NULL,NULL);
INSERT INTO `slangwords` VALUES (1176,'tradisionil','tradisional',NULL,NULL);
INSERT INTO `slangwords` VALUES (1177,'ujud','wujud',NULL,NULL);
INSERT INTO `slangwords` VALUES (1178,'mendifinisikan','mendefinisikan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1179,'rubuh','roboh',NULL,NULL);
INSERT INTO `slangwords` VALUES (1180,'silahkan','silakan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1181,'mumpung','selagi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1182,'problimatik','problematic',NULL,NULL);
INSERT INTO `slangwords` VALUES (1183,'tilpun','telepon',NULL,NULL);
INSERT INTO `slangwords` VALUES (1184,'penasehat','penasihat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1185,'spesis','spesies',NULL,NULL);
INSERT INTO `slangwords` VALUES (1186,'varitas','varietas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1187,'photo','foto',NULL,NULL);
INSERT INTO `slangwords` VALUES (1188,'produktifitas','produktivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1189,'subyek','subjek',NULL,NULL);
INSERT INTO `slangwords` VALUES (1190,'ahir','akhir',NULL,NULL);
INSERT INTO `slangwords` VALUES (1191,'on','ons',NULL,NULL);
INSERT INTO `slangwords` VALUES (1192,'eksport','ekspor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1193,'sukur','syukur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1194,'jendral','jenderal',NULL,NULL);
INSERT INTO `slangwords` VALUES (1195,'resiko','risiko',NULL,NULL);
INSERT INTO `slangwords` VALUES (1196,'survai','survei',NULL,NULL);
INSERT INTO `slangwords` VALUES (1197,'team','tim',NULL,NULL);
INSERT INTO `slangwords` VALUES (1198,'disel','diesel',NULL,NULL);
INSERT INTO `slangwords` VALUES (1199,'zone','zona',NULL,NULL);
INSERT INTO `slangwords` VALUES (1200,'filem','film',NULL,NULL);
INSERT INTO `slangwords` VALUES (1201,'manager','manajer',NULL,NULL);
INSERT INTO `slangwords` VALUES (1202,'dipersilakan','dipersilahkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1203,'kwalitas','kualitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1204,'mensukseskan','menyukseskan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1205,'baud','baut',NULL,NULL);
INSERT INTO `slangwords` VALUES (1206,'ekstrim','ekstrem',NULL,NULL);
INSERT INTO `slangwords` VALUES (1207,'managemen','manajemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1208,'wasallam','wasalam',NULL,NULL);
INSERT INTO `slangwords` VALUES (1209,'mengeritik','mengkritik',NULL,NULL);
INSERT INTO `slangwords` VALUES (1210,'ilmiawan','ilmuwan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1211,'menyolok','mencolok',NULL,NULL);
INSERT INTO `slangwords` VALUES (1212,'sekertaris','sekretaris',NULL,NULL);
INSERT INTO `slangwords` VALUES (1213,'prosentase','persentase',NULL,NULL);
INSERT INTO `slangwords` VALUES (1214,'pertanggungjawab','pertanggungjawaban',NULL,NULL);
INSERT INTO `slangwords` VALUES (1215,'perletakan','peletakan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1216,'dipindah','dipindahkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1217,'menterapkan','menerapkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1218,'memproklamirkan','memproklamasikan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1219,'insyaf','insaf',NULL,NULL);
INSERT INTO `slangwords` VALUES (1220,'trotoir','trotoar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1221,'dollar','dolar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1222,'setasiun','stasiun',NULL,NULL);
INSERT INTO `slangwords` VALUES (1223,'erobik','aerobic',NULL,NULL);
INSERT INTO `slangwords` VALUES (1224,'psikotest','psikotes',NULL,NULL);
INSERT INTO `slangwords` VALUES (1225,'melola','mengelola',NULL,NULL);
INSERT INTO `slangwords` VALUES (1226,'mengenyampingkan','mengesampingkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1227,'khutbah','khotbah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1228,'isteri','istri',NULL,NULL);
INSERT INTO `slangwords` VALUES (1229,'justeru','justru',NULL,NULL);
INSERT INTO `slangwords` VALUES (1230,'Sumatra','Sumatera',NULL,NULL);
INSERT INTO `slangwords` VALUES (1231,'negri','negeri',NULL,NULL);
INSERT INTO `slangwords` VALUES (1232,'Prancis','Perancis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1233,'krupuk','kerupuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (1234,'anugrah','anugerah',NULL,NULL);
INSERT INTO `slangwords` VALUES (1235,'rejim','rezim',NULL,NULL);
INSERT INTO `slangwords` VALUES (1236,'jamrud','zamrud',NULL,NULL);
INSERT INTO `slangwords` VALUES (1237,'saptu','sabtu',NULL,NULL);
INSERT INTO `slangwords` VALUES (1238,'sarap','saraf',NULL,NULL);
INSERT INTO `slangwords` VALUES (1239,'obrak-abrik','ubrak-abrik',NULL,NULL);
INSERT INTO `slangwords` VALUES (1240,'mangkok','mangkuk',NULL,NULL);
INSERT INTO `slangwords` VALUES (1241,'kaos','kaus',NULL,NULL);
INSERT INTO `slangwords` VALUES (1242,'bis','bus',NULL,NULL);
INSERT INTO `slangwords` VALUES (1243,'nomer','nomor',NULL,NULL);
INSERT INTO `slangwords` VALUES (1244,'punggawa','penggawa',NULL,NULL);
INSERT INTO `slangwords` VALUES (1245,'resleting','risleting',NULL,NULL);
INSERT INTO `slangwords` VALUES (1246,'kempes','kempis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1247,'intelejen','intelijen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1248,'vidio','video',NULL,NULL);
INSERT INTO `slangwords` VALUES (1249,'pinsil','pensil',NULL,NULL);
INSERT INTO `slangwords` VALUES (1250,'personil','personel',NULL,NULL);
INSERT INTO `slangwords` VALUES (1251,'musium','museum',NULL,NULL);
INSERT INTO `slangwords` VALUES (1252,'disain','desain',NULL,NULL);
INSERT INTO `slangwords` VALUES (1253,'dekrit','dekret',NULL,NULL);
INSERT INTO `slangwords` VALUES (1254,'diskripsi','deksripsi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1255,'debet','debit',NULL,NULL);
INSERT INTO `slangwords` VALUES (1256,'cendikiawan','cendekiawan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1257,'speda','sepeda',NULL,NULL);
INSERT INTO `slangwords` VALUES (1258,'cidera','cedera',NULL,NULL);
INSERT INTO `slangwords` VALUES (1259,'antri','antre',NULL,NULL);
INSERT INTO `slangwords` VALUES (1260,'afdol','afdal',NULL,NULL);
INSERT INTO `slangwords` VALUES (1261,'aktuil','aktual',NULL,NULL);
INSERT INTO `slangwords` VALUES (1262,'formil','formal',NULL,NULL);
INSERT INTO `slangwords` VALUES (1263,'materai','meterai',NULL,NULL);
INSERT INTO `slangwords` VALUES (1264,'kalendar','kalender',NULL,NULL);
INSERT INTO `slangwords` VALUES (1265,'parlamen','parlemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1266,'sekular','sekuler',NULL,NULL);
INSERT INTO `slangwords` VALUES (1267,'selular','seluler',NULL,NULL);
INSERT INTO `slangwords` VALUES (1268,'aritmatika','aritmetika',NULL,NULL);
INSERT INTO `slangwords` VALUES (1269,'amandemen','amendemen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1270,'adpokat','advokat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1271,'akte','akta',NULL,NULL);
INSERT INTO `slangwords` VALUES (1272,'cemilan','camilan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1273,'frase','frasa',NULL,NULL);
INSERT INTO `slangwords` VALUES (1274,'mesjid','masjid',NULL,NULL);
INSERT INTO `slangwords` VALUES (1275,'sekadar','sekedar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1276,'pengreditan','pengkreditan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1277,'sportip','sportif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1278,'sportifitas','sportivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1279,'obyek','objek',NULL,NULL);
INSERT INTO `slangwords` VALUES (1280,'terhempas','terempas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1281,'berfikir','berpikir',NULL,NULL);
INSERT INTO `slangwords` VALUES (1282,'himbau','imbau',NULL,NULL);
INSERT INTO `slangwords` VALUES (1283,'mempesona','memesona',NULL,NULL);
INSERT INTO `slangwords` VALUES (1284,'taxi','taksi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1285,'accu','Aki',NULL,NULL);
INSERT INTO `slangwords` VALUES (1286,'route','rute',NULL,NULL);
INSERT INTO `slangwords` VALUES (1287,'konggres','kongres',NULL,NULL);
INSERT INTO `slangwords` VALUES (1288,'Aquarium','Akuarium',NULL,NULL);
INSERT INTO `slangwords` VALUES (1289,'director','direktur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1290,'antar negara','antarnegara',NULL,NULL);
INSERT INTO `slangwords` VALUES (1291,'electronik','elektronik',NULL,NULL);
INSERT INTO `slangwords` VALUES (1292,'tekhnologi','teknologi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1293,'repertoire','repertoar',NULL,NULL);
INSERT INTO `slangwords` VALUES (1294,'relative','relatif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1295,'security','sekuritas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1296,'deputy','deputi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1297,'culture','kultur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1298,'diagnosa','diagnosis',NULL,NULL);
INSERT INTO `slangwords` VALUES (1299,'legalisir','legalisiasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1300,'akomodir','akomodasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1301,'abstrac','abstrak',NULL,NULL);
INSERT INTO `slangwords` VALUES (1302,'defaluasi','devaluasi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1303,'monarkhi','monarki',NULL,NULL);
INSERT INTO `slangwords` VALUES (1304,'structure','struktur',NULL,NULL);
INSERT INTO `slangwords` VALUES (1305,'theatre','teater',NULL,NULL);
INSERT INTO `slangwords` VALUES (1306,'University','Universitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1307,'lesung pipit','lesung pipi',NULL,NULL);
INSERT INTO `slangwords` VALUES (1308,'salat','sholat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1309,'disyahkan','disahkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1310,'fihak','pihak',NULL,NULL);
INSERT INTO `slangwords` VALUES (1311,'anggauta','anggota',NULL,NULL);
INSERT INTO `slangwords` VALUES (1312,'dipersilahkan','dipersilakan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1313,'langganan','pelanggan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1314,'utang','hutang',NULL,NULL);
INSERT INTO `slangwords` VALUES (1315,'dasa wisma','dasawisma',NULL,NULL);
INSERT INTO `slangwords` VALUES (1316,'pasca panen','pascapanen',NULL,NULL);
INSERT INTO `slangwords` VALUES (1317,'mengreditkan','mengkreditkan',NULL,NULL);
INSERT INTO `slangwords` VALUES (1318,'solat','sholat',NULL,NULL);
INSERT INTO `slangwords` VALUES (1319,'aktiv','aktif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1320,'aktipitas','aktivitas',NULL,NULL);
INSERT INTO `slangwords` VALUES (1321,'motiv','motif',NULL,NULL);
INSERT INTO `slangwords` VALUES (1322,'refrensi','referensi;',NULL,NULL);
/*!40000 ALTER TABLE `slangwords` ENABLE KEYS */;
UNLOCK TABLES;

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
